// ==UserScript==
// @name         Showdown FR
// @namespace    http://tampermonkey.net/
// @version      1.4.2
// @icon	 https://raw.githubusercontent.com/Webbeh/UserScript_ShowDown/master/icon2.png
// @description  Pokémon Showdown - Traduction française
// @author       Weby
// @license	 MIT
// @copyright	 2018, Weby (geeq.ch)
// @match        http://*.psim.us/*
// @match	 https://*.psim.us/*
// @match        http://replay.pokemonshowdown.com/*
// @match        https://replay.pokemonshowdown.com/*
// @match        http://play.pokemonshowdown.com/*
// @match        https://play.pokemonshowdown.com/*
// @match        http://pokemonshowdown.com/*
// @match        https://pokemonshowdown.com/*
// @grant        none
// @require      https://code.jQuery.com/jquery-2.1.4.min.js
// @updateURL	 https://openuserjs.org/meta/Weby/Showdown_FR.meta.js
// @run-at       document-end
// @homepageURL	 https://github.com/Webbeh/UserScript_ShowDown
// ==/UserScript==

// Afin de rajouter/modifier des traductions, dirigez-vous sur
// https://github.com/Webbeh/UserScript_ShowDown
// Forkez le projet, ajoutez vos traductions et faites un pull request !
//
// Une traduction par ligne, format :
//    "<à traduire>":"<traduction>",
// Si vous devez mettre un signe " , il faut l'écrire \"


var translations={
"Bulbasaur":"Bulbizarre",
"Ivysaur":"Herbizarre",
"Venusaur":"Florizarre",
"Charmander":"Salamèche",
"Charmeleon":"Reptincel",
"Charizard":"Dracaufeu",
"Squirtle":"Carapuce",
"Wartortle":"Carabaffe",
"Blastoise":"Tortank",
"Caterpie":"Chenipan",
"Metapod":"Chrysacier",
"Butterfree":"Papilusion",
"Weedle":"Aspicot",
"Kakuna":"Coconfort",
"Beedrill":"Dardargnan",
"Pidgey":"Roucool",
"Pidgeotto":"Roucoups",
"Pidgeot":"Roucarnage",
"Rattata":"Rattata",
"Raticate":"Rattatac",
"Spearow":"Piafabec",
"Fearow":"Rapasdepic",
"Ekans":"Abo",
"Arbok":"Arbok",
"Pikachu":"Pikachu",
"Raichu":"Raichu",
"Sandshrew":"Sabelette",
"Sandslash":"Sablaireau",
"Nidoran♀":"Nidoran♀",
"Nidorina":"Nidorina",
"Nidoqueen":"Nidoqueen",
"Nidoran♂":"Nidoran♂",
"Nidorino":"Nidorino",
"Nidoking":"Nidoking",
"Clefairy":"Mélofée",
"Clefable":"Mélodelfe",
"Vulpix":"Goupix",
"Ninetales":"Feunard",
"Jigglypuff":"Rondoudou",
"Wigglytuff":"Grodoudou",
"Zubat":"Nosferapti",
"Golbat":"Nosferalto",
"Oddish":"Mystherbe",
"Gloom":"Ortide",
"Vileplume":"Rafflesia",
"Paras":"Paras",
"Parasect":"Parasect",
"Venonat":"Mimitoss",
"Venomoth":"Aéromite",
"Diglett":"Taupiqueur",
"Dugtrio":"Triopikeur",
"Meowth":"Miaouss",
"Persian":"Persian",
"Psyduck":"Psykokwak",
"Golduck":"Akwakwak",
"Mankey":"Férosinge",
"Primeape":"Colossinge",
"Growlithe":"Caninos",
"Arcanine":"Arcanin",
"Poliwag":"Ptitard",
"Poliwhirl":"Têtarte",
"Poliwrath":"Tartard",
"Abra":"Abra",
"Kadabra":"Kadabra",
"Alakazam":"Alakazam",
"Machop":"Machoc",
"Machoke":"Machopeur",
"Machamp":"Mackogneur",
"Bellsprout":"Chétiflor",
"Weepinbell":"Boustiflor",
"Victreebel":"Empiflor",
"Tentacool":"Tentacool",
"Tentacruel":"Tentacruel",
"Geodude":"Racaillou",
"Graveler":"Gravalanch",
"Golem":"Grolem",
"Ponyta":"Ponyta",
"Rapidash":"Galopa",
"Slowpoke":"Ramoloss",
"Slowbro":"Flagadoss",
"Magnemite":"Magnéti",
"Magneton":"Magnéton",
"Farfetch'd":"Canarticho",
"Doduo":"Doduo",
"Dodrio":"Dodrio",
"Seel":"Otaria",
"Dewgong":"Lamantine",
"Grimer":"Tadmorv",
"Muk":"Grotadmorv",
"Shellder":"Kokiyas",
"Cloyster":"Crustabri",
"Gastly":"Fantominus",
"Haunter":"Spectrum",
"Gengar":"Ectoplasma",
"Onix":"Onix",
"Drowzee":"Soporifik",
"Hypno":"Hypnomade",
"Krabby":"Krabby",
"Kingler":"Krabboss",
"Voltorb":"Voltorbe",
"Electrode":"Électrode",
"Exeggcute":"Nœunœuf",
"Exeggutor":"Noadkoko",
"Cubone":"Osselait",
"Marowak":"Ossatueur",
"Hitmonlee":"Kicklee",
"Hitmonchan":"Tygnon",
"Lickitung":"Excelangue",
"Koffing":"Smogo",
"Weezing":"Smogogo",
"Rhyhorn":"Rhinocorne",
"Rhydon":"Rhinoféros",
"Chansey":"Leveinard",
"Tangela":"Saquedeneu",
"Kangaskhan":"Kangourex",
"Horsea":"Hypotrempe",
"Seadra":"Hypocéan",
"Goldeen":"Poissirène",
"Seaking":"Poissoroy",
"Staryu":"Stari",
"Starmie":"Staross",
"Mr.Mime":"M.Mime",
"Scyther":"Insécateur",
"Jynx":"Lippoutou",
"Electabuzz":"Élektek",
"Magmar":"Magmar",
"Pinsir":"Scarabrute",
"Tauros":"Tauros",
"Magikarp":"Magicarpe",
"Gyarados":"Léviator",
"Lapras":"Lokhlass",
"Ditto":"Métamorph",
"Eevee":"Évoli",
"Vaporeon":"Aquali",
"Jolteon":"Voltali",
"Flareon":"Pyroli",
"Porygon":"Porygon",
"Omanyte":"Amonita",
"Omastar":"Amonistar",
"Kabuto":"Kabuto",
"Kabutops":"Kabutops",
"Aerodactyl":"Ptéra",
"Snorlax":"Ronflex",
"Articuno":"Artikodin",
"Zapdos":"Électhor",
"Moltres":"Sulfura",
"Dratini":"Minidraco",
"Dragonair":"Draco",
"Dragonite":"Dracolosse",
"Mewtwo":"Mewtwo",
"Mew":"Mew",
"Chikorita":"Germignon",
"Bayleef":"Macronium",
"Meganium":"Méganium",
"Cyndaquil":"Héricendre",
"Quilava":"Feurisson",
"Typhlosion":"Typhlosion",
"Totodile":"Kaiminus",
"Croconaw":"Crocrodil",
"Feraligatr":"Aligatueur",
"Sentret":"Fouinette",
"Furret":"Fouinar",
"Hoothoot":"Hoothoot",
"Noctowl":"Noarfang",
"Ledyba":"Coxy",
"Ledian":"Coxyclaque",
"Spinarak":"Mimigal",
"Ariados":"Migalos",
"Crobat":"Nostenfer",
"Chinchou":"Loupio",
"Lanturn":"Lanturn",
"Pichu":"Pichu",
"Cleffa":"Mélo",
"Igglybuff":"Toudoudou",
"Togepi":"Togepi",
"Togetic":"Togetic",
"Natu":"Natu",
"Xatu":"Xatu",
"Mareep":"Wattouat",
"Flaaffy":"Lainergie",
"Ampharos":"Pharamp",
"Bellossom":"Joliflor",
"Marill":"Marill",
"Azumarill":"Azumarill",
"Sudowoodo":"Simularbre",
"Politoed":"Tarpaud",
"Hoppip":"Granivol",
"Skiploom":"Floravol",
"Jumpluff":"Cotovol",
"Aipom":"Capumain",
"Sunkern":"Tournegrin",
"Sunflora":"Héliatronc",
"Yanma":"Yanma",
"Wooper":"Axoloto",
"Quagsire":"Maraiste",
"Espeon":"Mentali",
"Umbreon":"Noctali",
"Murkrow":"Cornèbre",
"Slowking":"Roigada",
"Misdreavus":"Feuforêve",
"Unown":"Zarbi",
"Wobbuffet":"Qulbutoké",
"Girafarig":"Girafarig",
"Pineco":"Pomdepik",
"Forretress":"Foretress",
"Dunsparce":"Insolourdo",
"Gligar":"Scorplane",
"Steelix":"Steelix",
"Snubbull":"Snubbull",
"Granbull":"Granbull",
"Qwilfish":"Qwilfish",
"Scizor":"Cizayox",
"Shuckle":"Caratroc",
"Heracross":"Scarhino",
"Sneasel":"Farfuret",
"Teddiursa":"Teddiursa",
"Ursaring":"Ursaring",
"Slugma":"Limagma",
"Magcargo":"Volcaropod",
"Swinub":"Marcacrin",
"Piloswine":"Cochignon",
"Corsola":"Corayon",
"Remoraid":"Rémoraid",
"Octillery":"Octillery",
"Delibird":"Cadoizo",
"Mantine":"Démanta",
"Skarmory":"Airmure",
"Houndour":"Malosse",
"Houndoom":"Démolosse",
"Kingdra":"Hyporoi",
"Phanpy":"Phanpy",
"Donphan":"Donphan",
"Porygon2":"Porygon2",
"Stantler":"Cerfrousse",
"Smeargle":"Queulorior",
"Tyrogue":"Debugant",
"Hitmontop":"Kapoera",
"Smoochum":"Lippouti",
"Elekid":"Élekid",
"Magby":"Magby",
"Miltank":"Écrémeuh",
"Blissey":"Leuphorie",
"Raikou":"Raikou",
"Entei":"Entei",
"Suicune":"Suicune",
"Larvitar":"Embrylex",
"Pupitar":"Ymphect",
"Tyranitar":"Tyranocif",
"Lugia":"Lugia",
"Ho-Oh":"Ho-Oh",
"Celebi":"Celebi",
"Treecko":"Arcko",
"Grovyle":"Massko",
"Sceptile":"Jungko",
"Torchic":"Poussifeu",
"Combusken":"Galifeu",
"Blaziken":"Braségali",
"Mudkip":"Gobou",
"Marshtomp":"Flobio",
"Swampert":"Laggron",
"Poochyena":"Medhyèna",
"Mightyena":"Grahyèna",
"Zigzagoon":"Zigzaton",
"Linoone":"Linéon",
"Wurmple":"Chenipotte",
"Silcoon":"Armulys",
"Beautifly":"Charmillon",
"Cascoon":"Blindalys",
"Dustox":"Papinox",
"Lotad":"Nénupiot",
"Lombre":"Lombre",
"Ludicolo":"Ludicolo",
"Seedot":"Grainipiot",
"Nuzleaf":"Pifeuil",
"Shiftry":"Tengalice",
"Taillow":"Nirondelle",
"Swellow":"Hélédelle",
"Wingull":"Goélise",
"Pelipper":"Bekipan",
"Ralts":"Tarsal",
"Kirlia":"Kirlia",
"Gardevoir":"Gardevoir",
"Surskit":"Arakdo",
"Masquerain":"Maskadra",
"Shroomish":"Balignon",
"Breloom":"Chapignon",
"Slakoth":"Parecool",
"Vigoroth":"Vigoroth",
"Slaking":"Monaflèmit",
"Nincada":"Ningale",
"Ninjask":"Ninjask",
"Shedinja":"Munja",
"Whismur":"Chuchmur",
"Loudred":"Ramboum",
"Exploud":"Brouhabam",
"Makuhita":"Makuhita",
"Hariyama":"Hariyama",
"Azurill":"Azurill",
"Nosepass":"Tarinor",
"Skitty":"Skitty",
"Delcatty":"Delcatty",
"Sableye":"Ténéfix",
"Mawile":"Mysdibule",
"Aron":"Galekid",
"Lairon":"Galegon",
"Aggron":"Galeking",
"Meditite":"Méditikka",
"Medicham":"Charmina",
"Electrike":"Dynavolt",
"Manectric":"Élecsprint",
"Plusle":"Posipi",
"Minun":"Négapi",
"Volbeat":"Muciole",
"Illumise":"Lumivole",
"Roselia":"Rosélia",
"Gulpin":"Gloupti",
"Swalot":"Avaltout",
"Carvanha":"Carvanha",
"Sharpedo":"Sharpedo",
"Wailmer":"Wailmer",
"Wailord":"Wailord",
"Numel":"Chamallot",
"Camerupt":"Camérupt",
"Torkoal":"Chartor",
"Spoink":"Spoink",
"Grumpig":"Groret",
"Spinda":"Spinda",
"Trapinch":"Kraknoix",
"Vibrava":"Vibraninf",
"Flygon":"Libégon",
"Cacnea":"Cacnea",
"Cacturne":"Cacturne",
"Swablu":"Tylton",
"Altaria":"Altaria",
"Zangoose":"Mangriff",
"Seviper":"Séviper",
"Lunatone":"Séléroc",
"Solrock":"Solaroc",
"Barboach":"Barloche",
"Whiscash":"Barbicha",
"Corphish":"Écrapince",
"Crawdaunt":"Colhomard",
"Baltoy":"Balbuto",
"Claydol":"Kaorine",
"Lileep":"Lilia",
"Cradily":"Vacilys",
"Anorith":"Anorith",
"Armaldo":"Armaldo",
"Feebas":"Barpau",
"Milotic":"Milobellus",
"Castform":"Morphéo",
"Kecleon":"Kecleon",
"Shuppet":"Polichombr",
"Banette":"Branette",
"Duskull":"Skelénox",
"Dusclops":"Téraclope",
"Tropius":"Tropius",
"Chimecho":"Éoko",
"Absol":"Absol",
"Wynaut":"Okéoké",
"Snorunt":"Stalgamin",
"Glalie":"Oniglali",
"Spheal":"Obalie",
"Sealeo":"Phogleur",
"Walrein":"Kaimorse",
"Clamperl":"Coquiperl",
"Huntail":"Serpang",
"Gorebyss":"Rosabyss",
"Relicanth":"Relicanth",
"Luvdisc":"Lovdisc",
"Bagon":"Draby",
"Shelgon":"Drackhaus",
"Salamence":"Drattak",
"Beldum":"Terhal",
"Metang":"Métang",
"Metagross":"Métalosse",
"Regirock":"Regirock",
"Regice":"Regice",
"Registeel":"Registeel",
"Latias":"Latias",
"Latios":"Latios",
"Kyogre":"Kyogre",
"Groudon":"Groudon",
"Rayquaza":"Rayquaza",
"Jirachi":"Jirachi",
"Deoxys":"Deoxys",
"Turtwig":"Tortipouss",
"Grotle":"Boskara",
"Torterra":"Torterra",
"Chimchar":"Ouisticram",
"Monferno":"Chimpenfeu",
"Infernape":"Simiabraz",
"Piplup":"Tiplouf",
"Prinplup":"Prinplouf",
"Empoleon":"Pingoléon",
"Starly":"Étourmi",
"Staravia":"Étourvol",
"Staraptor":"Étouraptor",
"Bidoof":"Keunotor",
"Bibarel":"Castorno",
"Kricketot":"Crikzik",
"Kricketune":"Mélokrik",
"Shinx":"Lixy",
"Luxio":"Luxio",
"Luxray":"Luxray",
"Budew":"Rozbouton",
"Roserade":"Roserade",
"Cranidos":"Kranidos",
"Rampardos":"Charkos",
"Shieldon":"Dinoclier",
"Bastiodon":"Bastiodon",
"Burmy":"Cheniti",
"Wormadam":"Cheniselle",
"Mothim":"Papilord",
"Combee":"Apitrini",
"Vespiquen":"Apireine",
"Pachirisu":"Pachirisu",
"Buizel":"Mustébouée",
"Floatzel":"Mustéflott",
"Cherubi":"Ceribou",
"Cherrim":"Ceriflor",
"Shellos":"Sancoki",
"Gastrodon":"Tritosor",
"Ambipom":"Capidextre",
"Drifloon":"Baudrive",
"Drifblim":"Grodrive",
"Buneary":"Laporeille",
"Lopunny":"Lockpin",
"Mismagius":"Magirêve",
"Honchkrow":"Corboss",
"Glameow":"Chaglam",
"Purugly":"Chaffreux",
"Chingling":"Korillon",
"Stunky":"Moufouette",
"Skuntank":"Moufflair",
"Bronzor":"Archéomire",
"Bronzong":"Archéodong",
"Bonsly":"Manzaï",
"MimeJr.":"MimeJr",
"Happiny":"Ptiravi",
"Chatot":"Pijako",
"Spiritomb":"Spiritomb",
"Gible":"Griknot",
"Gabite":"Carmache",
"Garchomp":"Carchacrok",
"Munchlax":"Goinfrex",
"Riolu":"Riolu",
"Lucario":"Lucario",
"Hippopotas":"Hippopotas",
"Hippowdon":"Hippodocus",
"Skorupi":"Rapion",
"Drapion":"Drascore",
"Croagunk":"Cradopaud",
"Toxicroak":"Coatox",
"Carnivine":"Vortente",
"Finneon":"Écayon",
"Lumineon":"Luminéon",
"Mantyke":"Babimanta",
"Snover":"Blizzi",
"Abomasnow":"Blizzaroi",
"Weavile":"Dimoret",
"Magnezone":"Magnézone",
"Lickilicky":"Coudlangue",
"Rhyperior":"Rhinastoc",
"Tangrowth":"Bouldeneu",
"Electivire":"Élekable",
"Magmortar":"Maganon",
"Togekiss":"Togekiss",
"Yanmega":"Yanméga",
"Leafeon":"Phyllali",
"Glaceon":"Givrali",
"Gliscor":"Scorvol",
"Mamoswine":"Mammochon",
"Porygon-Z":"Porygon-Z",
"Gallade":"Gallame",
"Probopass":"Tarinorme",
"Dusknoir":"Noctunoir",
"Froslass":"Momartik",
"Rotom":"Motisma",
"Uxie":"Créhelf",
"Mesprit":"Créfollet",
"Azelf":"Créfadet",
"Dialga":"Dialga",
"Palkia":"Palkia",
"Heatran":"Heatran",
"Regigigas":"Regigigas",
"Giratina":"Giratina",
"Cresselia":"Cresselia",
"Phione":"Phione",
"Manaphy":"Manaphy",
"Darkrai":"Darkrai",
"Shaymin":"Shaymin",
"Arceus":"Arceus",
"Victini":"Victini",
"Snivy":"Vipélierre",
"Servine":"Lianaja",
"Serperior":"Majaspic",
"Tepig":"Gruikui",
"Pignite":"Grotichon",
"Emboar":"Roitiflam",
"Oshawott":"Moustillon",
"Dewott":"Mateloutre",
"Samurott":"Clamiral",
"Patrat":"Ratentif",
"Watchog":"Miradar",
"Lillipup":"Ponchiot",
"Herdier":"Ponchien",
"Stoutland":"Mastouffe",
"Purrloin":"Chacripan",
"Liepard":"Léopardus",
"Pansage":"Feuillajou",
"Simisage":"Feuiloutan",
"Pansear":"Flamajou",
"Simisear":"Flamoutan",
"Panpour":"Flotajou",
"Simipour":"Flotoutan",
"Munna":"Munna",
"Musharna":"Mushana",
"Pidove":"Poichigeon",
"Tranquill":"Colombeau",
"Unfezant":"Déflaisan",
"Blitzle":"Zébribon",
"Zebstrika":"Zéblitz",
"Roggenrola":"Nodulithe",
"Boldore":"Géolithe",
"Gigalith":"Gigalithe",
"Woobat":"Chovsourir",
"Swoobat":"Rhinolove",
"Drilbur":"Rototaupe",
"Excadrill":"Minotaupe",
"Audino":"Nanméouïe",
"Timburr":"Charpenti",
"Gurdurr":"Ouvrifier",
"Conkeldurr":"Bétochef",
"Tympole":"Tritonde",
"Palpitoad":"Batracné",
"Seismitoad":"Crapustule",
"Throh":"Judokrak",
"Sawk":"Karaclée",
"Sewaddle":"Larveyette",
"Swadloon":"Couverdure",
"Leavanny":"Manternel",
"Venipede":"Venipatte",
"Whirlipede":"Scobolide",
"Scolipede":"Brutapode",
"Cottonee":"Doudouvet",
"Whimsicott":"Farfaduvet",
"Petilil":"Chlorobule",
"Lilligant":"Fragilady",
"Basculin":"Bargantua",
"Sandile":"Mascaïman",
"Krokorok":"Escroco",
"Krookodile":"Crocorible",
"Darumaka":"Darumarond",
"Darmanitan":"Darumacho",
"Maractus":"Maracachi",
"Dwebble":"Crabicoque",
"Crustle":"Crabaraque",
"Scraggy":"Baggiguane",
"Scrafty":"Baggaïd",
"Sigilyph":"Cryptéro",
"Yamask":"Tutafeh",
"Cofagrigus":"Tutankafer",
"Tirtouga":"Carapagos",
"Carracosta":"Mégapagos",
"Archen":"Arkéapti",
"Archeops":"Aéroptéryx",
"Trubbish":"Miamiasme",
"Garbodor":"Miasmax",
"Zorua":"Zorua",
"Zoroark":"Zoroark",
"Minccino":"Chinchidou",
"Cinccino":"Pashmilla",
"Gothita":"Scrutella",
"Gothorita":"Mesmérella",
"Gothitelle":"Sidérella",
"Solosis":"Nucléos",
"Duosion":"Méios",
"Reuniclus":"Symbios",
"Ducklett":"Couaneton",
"Swanna":"Lakmécygne",
"Vanillite":"Sorbébé",
"Vanillish":"Sorboul",
"Vanilluxe":"Sorbouboul",
"Deerling":"Vivaldaim",
"Sawsbuck":"Haydaim",
"Emolga":"Emolga",
"Karrablast":"Carabing",
"Escavalier":"Lançargot",
"Foongus":"Trompignon",
"Amoonguss":"Gaulet",
"Frillish":"Viskuse",
"Jellicent":"Moyade",
"Alomomola":"Mamanbo",
"Joltik":"Statitik",
"Galvantula":"Mygavolt",
"Ferroseed":"Grindur",
"Ferrothorn":"Noacier",
"Klink":"Tic",
"Klang":"Clic",
"Klinklang":"Cliticlic",
"Tynamo":"Anchwatt",
"Eelektrik":"Lampéroie",
"Eelektross":"Ohmassacre",
"Elgyem":"Lewsor",
"Beheeyem":"Neitram",
"Litwick":"Funécire",
"Lampent":"Mélancolux",
"Chandelure":"Lugulabre",
"Axew":"Coupenotte",
"Fraxure":"Incisache",
"Haxorus":"Tranchodon",
"Cubchoo":"Polarhume",
"Beartic":"Polagriffe",
"Cryogonal":"Hexagel",
"Shelmet":"Escargaume",
"Accelgor":"Limaspeed",
"Stunfisk":"Limonde",
"Mienfoo":"Kungfouine",
"Mienshao":"Shaofouine",
"Druddigon":"Drakkarmin",
"Golett":"Gringolem",
"Golurk":"Golemastoc",
"Pawniard":"Scalpion",
"Bisharp":"Scalproie",
"Bouffalant":"Frison",
"Rufflet":"Furaiglon",
"Braviary":"Gueriaigle",
"Vullaby":"Vostourno",
"Mandibuzz":"Vaututrice",
"Heatmor":"Aflamanoir",
"Durant":"Fermite",
"Deino":"Solochi",
"Zweilous":"Diamat",
"Hydreigon":"Trioxhydre",
"Larvesta":"Pyronille",
"Volcarona":"Pyrax",
"Cobalion":"Cobaltium",
"Terrakion":"Terrakium",
"Virizion":"Viridium",
"Tornadus":"Boréas",
"Thundurus":"Fulguris",
"Reshiram":"Reshiram",
"Zekrom":"Zekrom",
"Landorus":"Démétéros",
"Kyurem":"Kyurem",
"Keldeo":"Keldeo",
"Meloetta":"Meloetta",
"Genesect":"Genesect",
"Chespin":"Marisson",
"Quilladin":"Boguérisse",
"Chesnaught":"Blindépique",
"Fennekin":"Feunnec",
"Braixen":"Roussil",
"Delphox":"Goupelin",
"Froakie":"Grenousse",
"Frogadier":"Croâporal",
"Greninja":"Amphinobi",
"Bunnelby":"Sapereau",
"Diggersby":"Excavarenne",
"Fletchling":"Passerouge",
"Fletchinder":"Braisillon",
"Talonflame":"Flambusard",
"Scatterbug":"Lépidonille",
"Spewpa":"Pérégrain",
"Vivillon":"Prismillon",
"Litleo":"Hélionceau",
"Pyroar":"Némélios",
"Flabébé":"Flabébé",
"Floette":"Floette",
"Florges":"Florges",
"Skiddo":"Cabriolaine",
"Gogoat":"Chevroum",
"Pancham":"Pandespiègle",
"Pangoro":"Pandarbare",
"Furfrou":"Couafarel",
"Espurr":"Psystigri",
"Meowstic":"Mistigrix",
"Honedge":"Monorpale",
"Doublade":"Dimoclès",
"Aegislash":"Exagide",
"Spritzee":"Fluvetin",
"Aromatisse":"Cocotine",
"Swirlix":"Sucroquin",
"Slurpuff":"Cupcanaille",
"Inkay":"Sepiatop",
"Malamar":"Sepiatroce",
"Binacle":"Opermine",
"Barbaracle":"Golgopathe",
"Skrelp":"Venalgue",
"Dragalge":"Kravarech",
"Clauncher":"Flingouste",
"Clawitzer":"Gamblast",
"Helioptile":"Galvaran",
"Heliolisk":"Iguolta",
"Tyrunt":"Ptyranidur",
"Tyrantrum":"Rexillius",
"Amaura":"Amagara",
"Aurorus":"Dragmara",
"Sylveon":"Nymphali",
"Hawlucha":"Brutalibré",
"Dedenne":"Dedenne",
"Carbink":"Strassie",
"Goomy":"Mucuscule",
"Sliggoo":"Colimucus",
"Goodra":"Muplodocus",
"Klefki":"Trousselin",
"Phantump":"Brocélôme",
"Trevenant":"Desséliande",
"Pumpkaboo":"Pitrouille",
"Gourgeist":"Banshitrouye",
"Bergmite":"Grelaçon",
"Avalugg":"Séracrawl",
"Noibat":"Sonistrelle",
"Noivern":"Bruyverne",
"Xerneas":"Xerneas",
"Yveltal":"Yveltal",
"Zygarde":"Zygarde",
"Diancie":"Diancie",
"Hoopa":"Hoopa",
"Volcanion":"Volcanion",
"Rowlet":"Brindibou",
"Dartrix":"Efflèche",
"Decidueye":"Archéduc",
"Litten":"Flamiaou",
"Torracat":"Matoufeu",
"Incineroar":"Félinferno",
"Popplio":"Otaquin",
"Brionne":"Otarlette",
"Primarina":"Oratoria",
"Pikipek":"Picassaut",
"Trumbeak":"Piclairon",
"Toucannon":"Bazoucan",
"Yungoos":"Manglouton",
"Gumshoos":"Argouste",
"Grubbin":"Larvibule",
"Charjabug":"Chrysapile",
"Vikavolt":"Lucanon",
"Crabrawler":"Crabagarre",
"Crabominable":"Crabominable",
"Oricorio":"Plumeline",
"Cutiefly":"Bombydou",
"Ribombee":"Rubombelle",
"Rockruff":"Rocabot",
"Lycanroc":"Lougaroc",
"Wishiwashi":"Froussardine",
"Mareanie":"Vorastérie",
"Toxapex":"Prédastérie",
"Mudbray":"Tiboudet",
"Mudsdale":"Bourrinos",
"Dewpider":"Araqua",
"Araquanid":"Tarenbulle",
"Fomantis":"Mimantis",
"Lurantis":"Floramantis",
"Morelull":"Spododo",
"Shiinotic":"Lampignon",
"Salandit":"Tritox",
"Salazzle":"Malamandre",
"Stufful":"Nounourson",
"Bewear":"Chelours",
"Bounsweet":"Croquine",
"Steenee":"Candine",
"Tsareena":"Sucreine",
"Comfey":"Guérilande",
"Oranguru":"Gouroutan",
"Passimian":"Quartermac",
"Wimpod":"Sovkipou",
"Golisopod":"Sarmuraï",
"Sandygast":"Bacabouh",
"Palossand":"Trépassable",
"Pyukumuku":"Concombaffe",
"Type:Null":"Type:0",
"Silvally":"Silvallié",
"Minior":"Météno",
"Komala":"Dodoala",
"Turtonator":"Boumata",
"Togedemaru":"Togedemaru",
"Mimikyu":"Mimiqui",
"Bruxish":"Denticrisse",
"Drampa":"Draïeul",
"Dhelmise":"Sinistrail",
"Jangmo-o":"Bébécaille",
"Hakamo-o":"Écaïd",
"Kommo-o":"Ékaïser",
"TapuKoko":"Tokorico",
"TapuLele":"Tokopiyon",
"TapuBulu":"Tokotoro",
"TapuFini":"Tokopisco",
"Cosmog":"Cosmog",
"Cosmoem":"Cosmovum",
"Solgaleo":"Solgaleo",
"Lunala":"Lunala",
"Nihilego":"Zéroïd",
"Buzzwole":"Mouscoto",
"Pheromosa":"Cancrelove",
"Xurkitree":"Câblifère",
"Celesteela":"Bamboiselle",
"Kartana":"Katagami",
"Guzzlord":"Engloutyran",
"Necrozma":"Necrozma",
"Magearna":"Magearna",
"Marshadow":"Marshadow",
"Poipole":"Vémini",
"Naganadel":"Mandrillon",
"Stakataka":"Ama-Ama",
"Blacephalon":"Pierroteknik",
"Zeraora":"Zeraora",

"[Gen 7] Random Battle":"[Gen 7] Combat Aléatoire",
"Add game":"Ajouter jeu",
"Format":"Format",
"Team":"Équipe",
"Battle!":"Combat!",
"Find a random opponent":"Trouver un adversaire aléatoire",
"Teambuilder":"Teambuilder",
"Ladder":"Échelle",
"Watch a battle":"Regarder un combat",
"Find a user":"Trouver un utilisateur",
"Did you have a good day?":"Avez-vous passé une bonne journée ?",
"[Gen 7] OU battle started between":"[Gen 7] Un combat OU a commencé entre",
"and":"et",
"used":"a utilisé",
"The opposing":"L'adversaire",
"restored a little HP using its Leftovers!":"a restauré quelques PV grâce à Restes !",
"forfeited":"a abandonné",
"fainted!":"est KO!",
"Random team":"Équipe aléatoire",
"Abilities":"Talents",
"Hidden Ability":"Talent caché",
"Will be":"Va être",
"after Mega Evolving.":"après avoir Mega-évolué.",
"Nickname":"Surnom",
"Item":"Objet",
"Ability":"Talent",
"Level":"Niveau",
"Gender":"Genre",
"Happiness":"Bonheur",
"Shiny":"Shiney",
"Moves":"Attaques",
"Copy":"Copier",
"Import/Export":"Importer / Exporter",
"Move":"Déplacer",
"Delete":"Effacer",
"Team":"Équipe",
"Validate":"Valider",
"Add Pokémon":"Ajouter un Pokémon",
"New Team":"Nouvelle équipe",
"Male":"Mâle",
"Female":"Femelle",
"Random":"Aléatoire",
"Format List":"Formatter la liste",
"List":"Lister",
"Edit":"Modifier",
"Save":"Sauvegarder",
"Switch":"Intervertir",
"It's super effective!":"C'est très efficace!",
"It's not very effective...":"Ce n'est pas très efficace...",
"lost":"a perdu ",
"of its health!":" de sa vie!",
", come back!":", reviens !",
"(exists)":"(existe)",
"Go!":"Go!",
"withdrew":"a retiré",
"sent out":"a envoyé",
"Change avatar":"Changer d'avatar",
"Password change":"Changer de mot de passe",
"Graphics":"Graphiques:",
"Layout:":"Disposition:",
"◫ Left and right panels":"◫ Panneaux à gauche et à droite",
"◻ Single panel":"◻ Un seul panneau",
"Background:":"Arrière-plan:",
"Change background":"Changer d'arrière-plan",
"Dark mode (beta)":"Mode nuit (beta)",
"Disable animations":"Désactiver les animations",
"Use BW sprites instead of XY models":"Utiliser les sprites de NB au lieu des modèles de XY",
"Use modern sprites for past generations":"Utiliser des sprites modernisés des générations précédentes",
"Chat":"Chat",
"Ignore tournaments":"Ignorer les tournois",
"Show PMs in chat rooms":"Afficher les messages privés dans le chat",
"Highlight when your name is said in chat":"Surligner les messages où vous êtes mentionnés",
"Notifications disappear automatically":"Faire disparaître automatiquement les notifications",
"Timestamps in chat rooms:":"Afficher les timestamps dans le chat:",
"Off":"Off",
"Timestamps in PMs:":"Afficher les timestamps dans les messages privés:",
"Chat preferences:":"Préférences du chat:",
"Edit formatting":"Éditer le format",
"You can choose to display formatted text as normal text":"Vous pouvez choisir d'afficher le texte formatté comme texte simple",
"Change name":"Changer de nom",
"Log out":"Déconnexion",

// Abilities Translation

"Stench":"Puanteur",
"Drizzle":"Crachin",
"Speed Boost":"Turbo",
"Battle Armor":"Armurbaston",
"Sturdy":"Fermeté",
"Damp":"Moiteur",
"Limber":"Échauffement",
"Sand Veil":"Voile Sable",
"Static":"Statik",
"Volt Absorb":"Absorb Volt",
"Water Absorb":"Absorb Eau",
"Oblivious":"Benêt",
"Cloud Nine":"Ciel Gris",
"Compound Eyes":"Œil Composé",
"Insomnia":"Insomnia",
"Color Change":"Déguisement",
"Immunity":"Vaccin",
"Flash Fire":"Torche",
"Shield Dust":"Écran Poudre",
"Own Tempo":"Tempo Perso",
"Suction Cups":"Ventouse",
"Intimidate":"Intimidation",
"Shadow Tag":"Marque Ombre",
"Rough Skin":"Peau Dure",
"Wonder Guard":"Garde Mystik",
"Levitate":"Lévitation",
"Effect Spore":"Pose Spore",
"Synchronize":"Synchro",
"Clear Body":"Corps Sain",
"Natural Cure":"Médic Nature",
"Lightning Rod":"Paratonnerre",
"Serene Grace":"Sérénité",
"Swift Swim":"Glissade",
"Chlorophyll":"Chlorophylle",
"Illuminate":"Lumiattirance",
"Trace":"Calque",
"Huge Power":"Coloforce",
"Poison Point":"Point Poison",
"Inner Focus":"Attention",
"Magma Armor":"Armumagma",
"Water Veil":"Ignifu-Voile",
"Magnet Pull":"Magnépiège",
"Soundproof":"Anti-Bruit",
"Rain Dish":"Cuvette",
"Sand Stream":"Sable Volant",
"Pressure":"Pression",
"Thick Fat":"Isograisse",
"Early Bird":"Matinal",
"Flame Body":"Corps Ardent",
"Run Away":"Fuite",
"Keen Eye":"Regard Vif",
"Hyper Cutter":"Hyper Cutter",
"Pickup":"Ramassage",
"Truant":"Absentéisme",
"Hustle":"Agitation",
"Cute Charm":"Joli Sourire",
"Plus":"Plus",
"Minus":"Minus",
"Forecast":"Météo",
"Sticky Hold":"Glue",
"Shed Skin":"Mue",
"Guts":"Cran",
"Marvel Scale":"Écaille Spéciale",
"Liquid Ooze":"Suintement",
"Overgrow":"Engrais",
"Blaze":"Brasier",
"Torrent":"Torrent",
"Swarm":"Essaim",
"Rock Head":"Tête de Roc",
"Drought":"Sécheresse",
"Arena Trap":"Piège Sable",
"Vital Spirit":"Esprit Vital",
"White Smoke":"Écran Fumée",
"Pure Power":"Force Pure",
"Shell Armor":"Coque Armure",
"Air Lock":"Air Lock",
"Tangled Feet":"Pieds Confus",
"Motor Drive":"Motorisé",
"Rivalry":"Rivalité",
"Steadfast":"Impassible",
"Snow Cloak":"Rideau Neige",
"Gluttony":"Gloutonnerie",
"Anger Point":"Colérique",
"Unburden":"Délestage",
"Heatproof":"Ignifugé",
"Simple":"Simple",
"Dry Skin":"Peau Sèche",
"Download":"Télécharge",
"Iron Fist":"Poing de Fer",
"Poison Heal":"Soin Poison",
"Adaptability":"Adaptabilité",
"Skill Link":"Multi-Coups",
"Hydration":"Hydratation",
"Solar Power":"Force Soleil",
"Quick Feet":"Pied Véloce",
"Normalize":"Normalise",
"Sniper":"Sniper",
"Magic Guard":"Garde Magik",
"No Guard":"Annule Garde",
"Stall":"Frein",
"Technician":"Technicien",
"Leaf Guard":"Feuille Garde",
"Klutz":"Maladresse",
"Mold Breaker":"Brise Moule",
"Super Luck":"Chanceux",
"Aftermath":"Boom Final",
"Anticipation":"Anticipation",
"Forewarn":"Prédiction",
"Unaware":"Inconscient",
"Tinted Lens":"Lentiteintée",
"Filter":"Filtre",
"Slow Start":"Début Calme",
"Scrappy":"Querelleur",
"Storm Drain":"Lavabo",
"Ice Body":"Corps Gel",
"Solid Rock":"Solide Roc",
"Snow Warning":"Alerte Neige",
"Honey Gather":"Cherche Miel",
"Frisk":"Fouille",
"Reckless":"Téméraire",
"Multitype":"Multitype",
"Flower Gift":"Don Floral",
"Bad Dreams":"Mauvais Rêve",
"Pickpocket":"Pickpocket",
"Sheer Force":"Sans Limite",
"Contrary":"Contestation",
"Unnerve":"Tension",
"Defiant":"Acharné",
"Defeatist":"Défaitiste",
"Cursed Body":"Corps Maudit",
"Healer":"Cœur Soin",
"Friend Guard":"Garde Amie",
"Weak Armor":"Armurouillée",
"Heavy Metal":"Heavy Metal",
"Light Metal":"Light Metal",
"Multiscale":"Multiécaille",
"Toxic Boost":"Rage Poison",
"Flare Boost":"Rage Brûlure",
"Harvest":"Récolte",
"Telepathy":"Télépathe",
"Moody":"Lunatique",
"Overcoat":"Envelocape",
"Poison Touch":"Toxitouche",
"Regenerator":"Régé-Force",
"Big Pecks":"Cœur de Coq",
"Sand Rush":"Baigne Sable",
"Wonder Skin":"Peau Miracle",
"Analytic":"Analyste",
"Illusion":"Illusion",
"Imposter":"Imposteur",
"Infiltrator":"Infiltration",
"Mummy":"Momie",
"Moxie":"Impudence",
"Justified":"Cœur Noble",
"Rattled":"Phobique",
"Magic Bounce":"Miroir Magik",
"Sap Sipper":"Herbivore",
"Prankster":"Farceur",
"Sand Force":"Force Sable",
"Iron Barbs":"Épine de Fer",
"Zen Mode":"Mode Transe",
"Victory Star":"Victorieux",
"Turboblaze":"TurboBrasier",
"Teravolt":"Téra-Voltage",
"Aroma Veil":"Aroma-Voile",
"Flower Veil":"Flora-Voile",
"Cheek Pouch":"Bajoues",
"Protean":"Protéen",
"Fur Coat":"Toison Épaisse",
"Magician":"Magicien",
"Bulletproof":"Pare-Balles",
"Competitive":"Battant",
"Strong Jaw":"Prognathe",
"Refrigerate":"Peau Gelée",
"Sweet Veil":"Gluco-Voile",
"Stance Change":"Déclic Tactique",
"Gale Wings":"Ailes Bourrasque",
"Mega Launcher":"Méga Blaster",
"Grass Pelt":"Toison Herbue",
"Symbiosis":"Symbiose",
"Tough Claws":"Griffe Dure",
"Pixilate":"Peau Féérique",
"Gooey":"Poisseux",
"Aerilate":"Peau Céleste",
"Parental Bond":"Amour Filial",
"Dark Aura":"Aura Ténébreuse",
"Fairy Aura":"Aura Féerique",
"Aura Break":"Aura Inversée",
"Primordial Sea":"Mer Primaire",
"Desolate Land":"Terre Finale",
"Delta Stream":"Souffle Delta",
"Stamina":"Endurance",
"Wimp Out":"Escampette",
"Emergency Exit":"Repli Tactique",
"Water Compaction":"Sable Humide",
"Merciless":"Cruauté",
"Shields Down":"Bouclier-Carcan",
"Stakeout":"Filature",
"Water Bubble":"Aquabulle",
"Steelworker":"Expert Acier",
"Berserk":"Dracolère",
"Slush Rush":"Chasse-Neige",
"Long Reach":"Longue Portée",
"Liquid Voice":"Hydrata-Son",
"Triage":"Prioguérison",
"Galvanize":"Peau Électrique",
"Surge Surfer":"Surf Caudal",
"Schooling":"Banc",
"Disguise":"Fantômasque",
"Battle Bond":"Synergie",
"Power Construct":"Rassemblement",
"Corrosion":"Corrosion",
"Comatose":"Hypersommeil",
"Queenly Majesty":"Prestance Royale",
"Innards Out":"Expuls'Organes",
"Dancer":"Danseuse",
"Battery":"Batterie",
"Fluffy":"Boule de Poils",
"Dazzling":"Corps Coloré",
"Soul-Heart":"Animacœur",
"Tangling Hair":"Mèche Rebelle",
"Receiver":"Receveur",
"Power of Alchemy":"Osmose",
"Beast Boost":"Boost Chimère",
"RKS System":"Système Alpha",
"Electric Surge":"Créa-Élec",
"Psychic Surge":"Créa-Psy",
"Misty Surge":"Créa-Brume",
"Grassy Surge":"Créa-Herbe",
"Full Metal Body":"Métallo-Garde",
"Shadow Shield":"Spectro-Bouclier",
"Prism Armor":"Prisme-Armure",

// Moves Translation

"Pound":"Écras'Face",
"Karate Chop":"Poing-Karaté",
"Double Slap":"Torgnoles",
"Comet Punch":"Poing Comète",
"Mega Punch":"Ultimapoing",
"Pay Day":"Jackpot",
"Fire Punch":"Poing de Feu",
"Ice Punch":"Poing-Glace",
"Thunder Punch":"Poing-Éclair",
"Scratch":"Griffe",
"Vice Grip":"Force Poigne",
"Guillotine":"Guillotine",
"Razor Wind":"Coupe-Vent",
"Swords Dance":"Danse-Lames",
"Cut":"Coupe",
"Gust":"Tornade",
"Wing Attack":"Cru-Aile",
"Whirlwind":"Cyclone",
"Fly":"Vol",
"Bind":"Étreinte",
"Slam":"Souplesse",
"Vine Whip":"Fouet Lianes",
"Stomp":"Écrasement",
"Double Kick":"Double Pied",
"Mega Kick":"Ultimawashi",
"Jump Kick":"Pied Sauté",
"Rolling Kick":"Mawashi Geri",
"Sand Attack":"Jet de Sable",
"Headbutt":"Coup d’Boule",
"Horn Attack":"Koud'Korne",
"Fury Attack":"Furie",
"Horn Drill":"Empal'Korne",
"Tackle":"Charge",
"Body Slam":"Plaquage",
"Wrap":"Ligotage",
"Take Down":"Bélier",
"Thrash":"Mania",
"Double-Edge":"Damoclès",
"Tail Whip":"Mimi-Queue",
"Poison Sting":"Dard-Venin",
"Twineedle":"Double-Dard",
"Pin Missile":"Dard-Nuée",
"Leer":"Groz'Yeux",
"Bite":"Morsure",
"Growl":"Rugissement",
"Roar":"Hurlement",
"Sing":"Berceuse",
"Supersonic":"Ultrason",
"Sonic Boom":"Sonicboom",
"Disable":"Entrave",
"Acid":"Acide",
  "Has a 10% chance to lower the target's Special Defense by 1 stage.":"Acide a 10% de chances de baisser la Défense Spéciale de l'adversaire, en plus d'infliger des dégâts.",
  "10% chance to lower the foe(s) Sp. Def by 1.":"10% de chances de réduire la Déf.Sp. de l'ennemi de 1.",
  "Has a 10% chance to lower the target's Defense by 1 stage.":"Inflige des dégats et a 10% de chances de diminuer la Défense de l'adversaire.",
  "10% chance to lower the foe(s) Defense by 1.":"10% de chances de diminuer la Défense de 1.",
  "Has a 33% chance to lower the target's Defense by 1 stage.":"A 33% de chances de réduire d'un niveau la Défense du Pokémon adverse, en plus d'infliger des dégâts.",
  "33% chance to lower the target's Defense by 1.":"33% de chances de diminuer la Défense de 1.",
  "10% chance to lower the target's Defense by 1.":"A 10% de chances de réduire d'un niveau la Défense du Pokémon adverse, en plus d'infliger des dégâts.",
"Ember":"Flammèche",
"Flamethrower":"Lance-Flammes",
"Mist":"Brume",
"Water Gun":"Pistolet à O",
"Hydro Pump":"Hydrocanon",
"Surf":"Surf",
"Ice Beam":"Laser Glace",
"Blizzard":"Blizzard",
"Psybeam":"Rafale Psy",
"Bubble Beam":"Bulles d’O",
"Aurora Beam":"Onde Boréale",
"Hyper Beam":"Ultralaser",
"Peck":"Picpic",
"Drill Peck":"Bec Vrille",
"Submission":"Sacrifice",
"Low Kick":"Balayage",
"Counter":"Riposte",
"Seismic Toss":"Frappe Atlas",
"Strength":"Force",
"Absorb":"Vol-Vie",
  "The user recovers 1/2 the HP lost by the target, rounded half up. If Big Root is held by the user, the HP recovered is 1.3x normal, rounded half down.":"Le pokémon récupère la moitié des PV perdus par la cible, arrondis à la moitié. Si Grosse Racine est tenu par le pokémon, les PV récupérés sont multipliés par 1,3, arrondis à la moitié.",
  "User recovers 50% of the damage dealt.":"L'utilisateur récupère 50% des dégâts infligés.",
  "The user recovers 1/2 the HP lost by the target, rounded down. If this move breaks the target's substitute, the user does not recover any HP.":"L'utilisateur récupère 50% des dégâts infligés.",
  "The user recovers 1/2 the HP lost by the target, rounded down. If the target has a substitute, this move misses.":"L'utilisateur récupère 50% des dégâts infligés.",
  "The user recovers 1/2 the HP lost by the target, rounded down.":"L'utilisateur récupère 50% des dégâts infligés.",
  "The user recovers 1/2 the HP lost by the target, rounded down. If Big Root is held by the user, the HP recovered is 1.3x normal, rounded down.":"Le pokémon récupère la moitié des PV perdus par la cible, arrondis à la moitié. Si Grosse Racine est tenu par le pokémon, les PV récupérés sont multipliés par 1,3, arrondis à la moitié.",
"Mega Drain":"Méga-Sangsue",
"Leech Seed":"Vampigraine",
"Growth":"Croissance",
"Razor Leaf":"Tranch'Herbe",
"Solar Beam":"Lance-Soleil",
"Poison Powder":"Poudre Toxik",
"Stun Spore":"Para-Spore",
"Sleep Powder":"Poudre Dodo",
"Petal Dance":"Danse-Fleur",
"String Shot":"Sécrétion",
"Dragon Rage":"Draco-Rage",
"Fire Spin":"Danse Flamme",
"Thunder Shock":"Éclair",
"Thunderbolt":"Tonnerre",
"Thunder Wave":"Cage-Éclair",
"Thunder":"Fatal-Foudre",
"Rock Throw":"Jet-Pierres",
"Earthquake":"Séisme",
"Fissure":"Abîme",
"Dig":"Tunnel",
"Toxic":"Toxik",
"Confusion":"Choc Mental",
"Psychic":"Psyko",
"Hypnosis":"Hypnose",
"Meditate":"Yoga",
"Agility":"Hâte",
  "Raises the user's Speed by 2 stages.":"Augmente de 2 niveaux la Vitesse du lanceur.",
  "Raises the user's Speed by 2.":"Augmente la Vitesse du lanceur de 2.",
"Quick Attack":"Vive-Attaque",
"Rage":"Frénésie",
"Teleport":"Téléport",
"Night Shade":"Ombre Nocturne",
"Mimic":"Copie",
"Screech":"Grincement",
"Double Team":"Reflet",
"Recover":"Soin",
"Harden":"Armure",
"Minimize":"Lilliput",
"Smokescreen":"Brouillard",
"Confuse Ray":"Onde Folie",
"Withdraw":"Repli",
"Defense Curl":"Boul'Armure",
"Barrier":"Bouclier",
"Light Screen":"Mur Lumière",
"Haze":"Buée Noire",
"Reflect":"Protection",
"Focus Energy":"Puissance",
"Bide":"Patience",
"Metronome":"Métronome",
"Mirror Move":"Mimique",
"Self-Destruct":"Destruction",
"Egg Bomb":"Bomb'Œuf",
"Lick":"Léchouille",
"Smog":"Purédpois",
"Sludge":"Détritus",
"Bone Club":"Massd'Os",
"Fire Blast":"Déflagration",
"Waterfall":"Cascade",
"Clamp":"Claquoir",
"Swift":"Météores",
"Skull Bash":"Coud'Krâne",
"Spike Cannon":"Picanon",
"Constrict":"Constriction",
"Amnesia":"Amnésie",
  "Raises the user's Special Defense by 2 stages.":"Augmente la Défense Spéciale de son utilisateur de 2.",
  "Raises the user's Sp. Def by 2.":"Augmente la Def.Spé. de 2.",
  "Raises the user's Special by 2 stages.":"Augmente le Spécial de l'utilisateur de 2.",
  "Raises the user's Special by 2.":"Augmente le Spécial de 2.",
"Kinesis":"Télékinésie",
"Soft-Boiled":"E-Coque",
"High Jump Kick":"Pied-voltige",
"Glare":"Regard Médusant",
"Dream Eater":"Dévorêve",
"Poison Gas":"Gaz Toxik",
"Barrage":"Pilonnage",
"Leech Life":"Vampirisme",
"Lovely Kiss":"Grobisou",
"Sky Attack":"Piqué",
"Transform":"Morphing",
"Bubble":"Écume",
"Dizzy Punch":"Uppercut",
"Spore":"Spore",
"Flash":"Flash",
"Psywave":"Vague Psy",
"Splash":"Trempette",
"Acid Armor":"Acidarmure",
  "Raises the user's Defense by 2 stages.":"Augmente la Défense du lanceur de 2.",
  "Raises the user's Defense by 2.":"Augmente la Défense du lanceur de 2.",
"Crabhammer":"Pince-Masse",
"Explosion":"Explosion",
"Fury Swipes":"Combo-Griffe",
"Bonemerang":"Osmerang",
"Rest":"Repos",
"Rock Slide":"Éboulement",
"Hyper Fang":"Croc de Mort",
"Sharpen":"Affûtage",
"Conversion":"Conversion",
"Tri Attack":"Triplattaque",
"Super Fang":"Croc Fatal",
"Slash":"Tranche",
"Substitute":"Clonage",
"Struggle":"Lutte",
"Sketch":"Gribouille",
"Triple Kick":"Triple Pied",
"Thief":"Larcin",
"Spider Web":"Toile",
"Mind Reader":"Lire-Esprit",
"Nightmare":"Cauchemar",
"Flame Wheel":"Roue de Feu",
"Snore":"Ronflement",
"Curse":"Malédiction",
"Flail":"Fléau",
"Conversion 2":"Conversion2",
"Aeroblast":"Aéroblast",
  "Has a higher chance for a critical hit.":"A un haut taux de coups critiques.",
  "High critical hit ratio.":"Taux de critiques élevé.",
"Cotton Spore":"Spore Coton",
"Reversal":"Contre",
"Spite":"Dépit",
"Powder Snow":"Poudreuse",
"Protect":"Abri",
"Mach Punch":"Mach Punch",
"Scary Face":"Grimace",
"Feint Attack":"Feinte",
"Sweet Kiss":"Doux Baiser",
"Belly Drum":"Cognobidon",
"Sludge Bomb":"Bomb-Beurk",
"Mud-Slap":"Coud'Boue",
"Octazooka":"Octazooka",
"Spikes":"Picots",
"Zap Cannon":"Élecanon",
"Foresight":"Clairvoyance",
"Destiny Bond":"Prélèvem. Destin",
"Perish Song":"Requiem",
"Icy Wind":"Vent Glace",
"Detect":"Détection",
"Bone Rush":"Charge-Os",
"Lock-On":"Verrouillage",
"Outrage":"Colère",
"Sandstorm":"Tempête de Sable",
"Giga Drain":"Giga-Sangsue",
"Endure":"Ténacité",
"Charm":"Charme",
"Rollout":"Roulade",
"False Swipe":"Faux-Chage",
"Swagger":"Vantardise",
"Milk Drink":"Lait à Boire",
"Spark":"Étincelle",
"Fury Cutter":"Taillade",
"Steel Wing":"Aile d’Acier",
"Mean Look":"Regard Noir",
"Attract":"Attraction",
"Sleep Talk":"Blabla Dodo",
"Heal Bell":"Glas de Soin",
"Return":"Retour",
"Present":"Cadeau",
"Frustration":"Frustration",
"Safeguard":"Rune Protect",
"Pain Split":"Balance",
"Sacred Fire":"Feu Sacré",
"Magnitude":"Ampleur",
"Dynamic Punch":"Dynamopoing",
"Megahorn":"Mégacorne",
"Dragon Breath":"Dracosouffle",
"Baton Pass":"Relais",
"Encore":"Encore",
"Pursuit":"Poursuite",
"Rapid Spin":"Tour Rapide",
"Sweet Scent":"Doux Parfum",
"Iron Tail":"Queue de Fer",
"Metal Claw":"Griffe Acier",
"Vital Throw":"Corps Perdu",
"Morning Sun":"Aurore",
"Synthesis":"Synthèse",
"Moonlight":"Rayon Lune",
"Hidden Power":"Puissance Cachée",
"Cross Chop":"Coup-Croix",
"Twister":"Ouragan",
"Rain Dance":"Danse Pluie",
"Sunny Day":"Zénith",
"Crunch":"Mâchouille",
"Mirror Coat":"Voile Miroir",
"Psych Up":"Boost",
"Extreme Speed":"Vit. Extreme",
"Ancient Power":"Pouvoir Antique",
  "Has a 10% chance to raise the user's Attack, Defense, Special Attack, Special Defense, and Speed by 1 stage.":"A 10% de chances d'augmenter de 1 toutes les stats de l'utilisateur.",
  "10% chance to raise all stats by 1 (not acc/eva).":"10% de chances d'augmenter toutes les stats de 1.",
"Shadow Ball":"Ball'Ombre",
"Apple Acid":"Acide Malique",
  "Has a 100% chance to lower the target's Special Defense by 1 stage.":"Le lanceur attaque son adversaire avec un liquide corrosif crée à partir d'une pomme acide. Baisse la Défense Spéciale de la cible.",
"Future Sight":"Prescience",
"Rock Smash":"Éclate-Roc",
"Whirlpool":"Siphon",
"Beat Up":"Baston",
"Fake Out":"Bluff",
"Uproar":"Brouhaha",
"Stockpile":"Stockage",
"Spit Up":"Relâche",
"Swallow":"Avale",
"Heat Wave":"Canicule",
"Hail":"Grêle",
"Torment":"Tourmente",
"Flatter":"Flatterie",
"Will-O-Wisp":"Feu Follet",
"Memento":"Souvenir",
"Facade":"Façade",
"Focus Punch":"Mitra-Poing",
"Smelling Salts":"Stimulant",
"Follow Me":"Par Ici",
"Nature Power":"Force-Nature",
"Charge":"Chargeur",
"Taunt":"Provoc",
"Helping Hand":"Coup d'Main",
"Trick":"Tourmagik",
"Role Play":"Imitation",
"Wish":"Vœu",
"Assist":"Assistance",
"Ingrain":"Racines",
"Superpower":"Surpuissance",
"Magic Coat":"Reflet Magik",
"Recycle":"Recyclage",
"Revenge":"Vendetta",
"Brick Break":"Casse-Brique",
"Yawn":"Bâillement",
"Knock Off":"Sabotage",
"Endeavor":"Effort",
"Eruption":"Éruption",
"Skill Swap":"Échange",
"Imprison":"Possessif",
"Refresh":"Régénération",
"Grudge":"Rancune",
"Snatch":"Saisie",
"Secret Power":"Force Cachée",
"Dive":"Plongée",
"Arm Thrust":"Cogne",
"Camouflage":"Camouflage",
"Tail Glow":"Lumiqueue",
"Luster Purge":"Lumi-Éclat",
"Mist Ball":"Ball'Brume",
"Feather Dance":"Danse-Plume",
"Teeter Dance":"Danse-Folle",
"Blaze Kick":"Pied Brûleur",
"Mud Sport":"Lance-Boue",
"Ice Ball":"Ball'Glace",
"Needle Arm":"Poing Dard",
"Slack Off":"Paresse",
"Hyper Voice":"Mégaphone",
"Poison Fang":"Crochet Venin",
"Crush Claw":"Éclate Griffe",
"Blast Burn":"Rafale Feu",
"Hydro Cannon":"Hydroblast",
"Meteor Mash":"Poing Météore",
"Astonish":"Étonnement",
"Weather Ball":"Ball'Météo",
"Aromatherapy":"Aromathérapie",
"Fake Tears":"Croco Larme",
"Air Cutter":"Tranch'Air",
  "Has a higher chance for a critical hit.":"Possède un taux de coups critiques élevé.",
  "High critical hit ratio. Hits adjacent foes.":"Taux de coups critiques élevé. Frappe les ennemis adjacents.",
"Overheat":"Surchauffe",
"Odor Sleuth":"Flair",
"Rock Tomb":"Tomberoche",
"Silver Wind":"Vent Argenté",
"Metal Sound":"Strido-Son",
"Grass Whistle":"Siffl'Herbe",
"Tickle":"Chatouille",
"Cosmic Power":"Force Cosmik",
"Water Spout":"Giclédo",
"Signal Beam":"Rayon Signal",
"Shadow Punch":"Poing Ombre",
"Extrasensory":"Extrasenseur",
"Sky Uppercut":"Stratopercut",
"Sand Tomb":"Tourbi-Sable",
"Sheer Cold":"Glaciation",
"Muddy Water":"Ocroupi",
"Bullet Seed":"Balle Graine",
"Aerial Ace":"Aéropique",
  "This move does not check accuracy.":"N'échoue jamais.",
"Icicle Spear":"Stalagtite",
"Iron Defense":"Mur de Fer",
"Block":"Barrage",
"Howl":"Grondement",
"Dragon Claw":"Dracogriffe",
"Frenzy Plant":"Végé-Attak",
"Bulk Up":"Gonflette",
"Bounce":"Rebond",
"Mud Shot":"Tir de Boue",
"Poison Tail":"Queue-Poison",
"Covet":"Implore",
"Volt Tackle":"Électacle",
"Magical Leaf":"Feuillemagik",
"Water Sport":"Tourniquet",
"Calm Mind":"Plénitude",
"Leaf Blade":"Lame-Feuille",
"Dragon Dance":"Danse Draco",
"Rock Blast":"Boule Roc",
"Shock Wave":"Onde de Choc",
"Water Pulse":"Vibraqua",
"Doom Desire":"Carnareket",
"Psycho Boost":"Psycho Boost",
"Roost":"Atterrissage",
"Gravity":"Gravité",
"Miracle Eye":"Œil Miracle",
"Wake-Up Slap":"Réveil Forcé",
"Hammer Arm":"Marto-Poing",
"Gyro Ball":"Gyroballe",
"Healing Wish":"Vœu Soin",
"Brine":"Saumure",
"Natural Gift":"Don Naturel",
"Feint":"Ruse",
"Pluck":"Picore",
"Tailwind":"Vent Arrière",
"Acupressure":"Acupression",
  "Raises a random stat by 2 stages as long as the stat is not already at stage 6. The user can choose to use this move on itself or an adjacent ally. Fails if no stat stage can be raised or if used on an ally with a substitute.":"Augmente une statistique aléatoire de 2 niveaux tant que la statistique n'est pas déjà au niveau 6. L'utilisateur peut choisir d'utiliser ce mouvement sur lui-même ou sur un allié adjacent. Échoue si aucun niveau de statistique ne peut être augmenté ou s'il est utilisé sur un allié avec un substitut.",
  "Raises a random stat of the user or an ally by 2.":"Augmente une statistique aléatoire de l'utilisateur ou d'un allié de 2.",
  "Raises a random stat by 2 stages as long as the stat is not already at stage 6. The user can choose to use this move on itself or an ally. Fails if no stat stage can be raised or if the user or ally has a substitute.":"Augmente une statistique aléatoire de 2 niveaux tant que la statistique n'est pas déjà au niveau 6. L'utilisateur peut choisir d'utiliser ce mouvement sur lui-même ou sur un allié adjacent. Échoue si aucun niveau de statistique ne peut être augmenté ou s'il est utilisé sur un allié avec un substitut.",
"Metal Burst":"Fulmifer",
"U-turn":"Demi-Tour",
"Close Combat":"Close Combat",
"Payback":"Représailles",
"Assurance":"Assurance",
"Embargo":"Embargo",
"Fling":"Dégommage",
"Psycho Shift":"Échange Psy",
"Trump Card":"Atout",
"Heal Block":"Anti-Soin",
"Wring Out":"Essorage",
"Power Trick":"Astuce Force",
"Gastro Acid":"Suc Digestif",
"Lucky Chant":"Air Veinard",
"Me First":"Moi d'Abord",
"Copycat":"Photocopie",
"Power Swap":"Permuforce",
"Guard Swap":"Permugarde",
"Punishment":"Punition",
"Last Resort":"Dernier Recours",
"Worry Seed":"Soucigraine",
"Sucker Punch":"Coup Bas",
"Toxic Spikes":"Pics Toxik",
"Heart Swap":"Permucœur",
"Aqua Ring":"Anneau Hydro",
"Magnet Rise":"Vol Magnétik",
"Flare Blitz":"Boutefeu",
"Force Palm":"Forte-Paume",
"Aura Sphere":"Aurasphère",
"Rock Polish":"Poliroche",
"Poison Jab":"Direct Toxik",
"Dark Pulse":"Vibrobscur",
"Night Slash":"Tranche-Nuit",
"Aqua Tail":"Hydroqueue",
"Seed Bomb":"Canon Graine",
"Air Slash":"Lame d'Air",
  "Has a 30% chance to make the target flinch.":"Possède 30% de chances d'apeurer la cible.",
  "30% chance to make the target flinch.":"30% de chances d'apeurer la cible.",
"X-Scissor":"Plaie-Croix",
"Bug Buzz":"Bourdon",
"Dragon Pulse":"Dracochoc",
"Dragon Rush":"Dracocharge",
"Power Gem":"Rayon Gemme",
"Drain Punch":"Vampipoing",
"Vacuum Wave":"Onde Vide",
"Focus Blast":"Exploforce",
"Energy Ball":"Éco-Sphère",
"Brave Bird":"Rapace",
"Earth Power":"Telluriforce",
"Switcheroo":"Passe-Passe",
"Giga Impact":"Giga Impact",
"Nasty Plot":"Machination",
"Bullet Punch":"Pisto-Poing",
"Avalanche":"Avalanche",
"Ice Shard":"Éclats Glace",
"Shadow Claw":"Griffe Ombre",
"Thunder Fang":"Crocs Éclair",
"Ice Fang":"Crocs Givre",
"Fire Fang":"Crocs Feu",
"Shadow Sneak":"Ombre Portée",
"Mud Bomb":"Boue-Bombe",
"Psycho Cut":"Coupe Psycho",
"Zen Headbutt":"Psykoud'Boul",
"Mirror Shot":"Miroi-Tir",
"Flash Cannon":"Luminocanon",
"Rock Climb":"Escalade",
"Defog":"Anti-Brume",
"Trick Room":"Distorsion",
"Draco Meteor":"Draco Météore",
"Discharge":"Coup d'Jus",
"Lava Plume":"Ébullilave",
"Leaf Storm":"Tempête Verte",
"Power Whip":"Mégafouet",
"Rock Wrecker":"Roc-Boulet",
"Cross Poison":"Poison-Croix",
"Gunk Shot":"Détricanon",
"Iron Head":"Tête de Fer",
"Magnet Bomb":"Bombaimant",
"Stone Edge":"Lame de Roc",
"Captivate":"Séduction",
"Stealth Rock":"Piège de Roc",
"Grass Knot":"Nœud Herbe",
"Chatter":"Babil",
"Judgment":"Jugement",
"Bug Bite":"Piqûre",
"Charge Beam":"Rayon Chargé",
"Wood Hammer":"Martobois",
"Aqua Jet":"Aqua-Jet",
"Attack Order":"Appel Attaque",
"Defend Order":"Appel Défense",
"Heal Order":"Appel Soins",
"Head Smash":"Fracass'Tête",
"Double Hit":"Coup Double",
"Roar of Time":"Hurle-Temps",
"Spacial Rend":"Spatio-Rift",
"Lunar Dance":"Danse-Lune",
"Crush Grip":"Presse",
"Magma Storm":"Vortex Magma",
"Dark Void":"Trou Noir",
"Seed Flare":"Fulmigraine",
"Ominous Wind":"Vent Mauvais",
"Shadow Force":"Revenant",
"Hone Claws":"Aiguisage",
"Wide Guard":"Garde Large",
"Guard Split":"Partage Garde",
"Power Split":"Partage Force",
"Wonder Room":"Zone Étrange",
"Psyshock":"Choc Psy",
"Venoshock":"Choc Venin",
"Autotomize":"Allègement",
"Rage Powder":"Poudre Fureur",
"Telekinesis":"Lévikinésie",
"Magic Room":"Zone Magique",
"Smack Down":"Anti-Air",
"Storm Throw":"Yama Arashi",
"Flame Burst":"Rebondifeu",
"Sludge Wave":"Cradovague",
"Quiver Dance":"Papillodanse",
"Heavy Slam":"Tacle Lourd",
"Synchronoise":"Synchropeine",
"Electro Ball":"Boule Élek",
"Soak":"Détrempage",
"Flame Charge":"Nitrocharge",
"Coil":"Enroulement",
"Low Sweep":"Balayette",
"Acid Spray":"Bombe Acide",
  "Has a 100% chance to lower the target's Special Defense by 2 stages.":"A 100% de chances de beaucoup diminuer la Défense Spéciale.",
  "100% chance to lower the target's Sp. Def by 2.":"A 100% de chances de diminuer la Déf.Spé. de 2.",
"Foul Play":"Tricherie",
"Simple Beam":"Rayon Simple",
"Entrainment":"Ten-danse",
"After You":"Après Vous",
  "The target makes its move immediately after the user this turn, no matter the priority of its selected move. Fails if the target would have moved next anyway, or if the target already moved this turn.":"Ne fonctionne que si la cible est plus lente que le lanceur, permet de la faire frapper juste après ce dernier.",
  "The target makes its move right after the user.":"La cible se déplace juste après l'utilisateur.",
  "  [TARGET] took the kind offer!":"  [TARGET] a accepté l'offre !",
"Round":"Chant Canon",
"Echoed Voice":"Écho",
"Chip Away":"Attrition",
"Clear Smog":"Bain de Smog",
"Stored Power":"Force Ajoutée",
"Quick Guard":"Prévention",
"Ally Switch":"Interversion",
  "The user swaps positions with its ally. Fails if the user is the only Pokemon on its side.":"Permet de changer sa position avec un allié. La capacité échoue si le lanceur est au milieu du terrain lors des combats triples.",
  "The user swaps positions with its ally.":"L'utilisateur échange de position avec son allié.",
  "The user swaps positions with its ally on the opposite side of the field. Fails if there is no Pokemon at that position, if the user is the only Pokemon on its side, or if the user is in the middle.":"Permet de changer sa position avec un allié, au cours d'un combat double ou triple. La capacité échoue si le lanceur est au milieu du terrain lors des combats triples.",
  "Switches position with the ally on the far side.":"Change de position avec l'allié de l'autre côté.",
"Scald":"Ébullition",
"Shell Smash":"Exuviation",
"Heal Pulse":"Vibra Soin",
"Hex":"Châtiment",
"Sky Drop":"Chute Libre",
"Shift Gear":"Changement Vitesse",
"Circle Throw":"Projection",
"Incinerate":"Calcination",
"Quash":"À la Queue",
"Acrobatics":"Acrobatie",
  "Power doubles if the user has no held item.":"La puissance double quand son lanceur ne tient pas d'objet.",
"Reflect Type":"Copie Type",
"Retaliate":"Vengeance",
"Final Gambit":"Tout ou Rien",
"Bestow":"Passe-Cadeau",
"Inferno":"Feu d'Enfer",
"Water Pledge":"Aire d'Eau",
"Fire Pledge":"Aire de Feu",
"Grass Pledge":"Aire de Plante",
"Volt Switch":"Change Éclair",
"Struggle Bug":"Survinsecte",
"Bulldoze":"Piétisol",
"Frost Breath":"Souffle Glacé",
"Dragon Tail":"Draco-Queue",
"Work Up":"Rengorgement",
"Electroweb":"Toile Élek",
"Wild Charge":"Éclair Fou",
"Drill Run":"Tunnelier",
"Dual Chop":"Double Baffe",
"Heart Stamp":"Crèvecœur",
"Horn Leech":"Encornebois",
"Sacred Sword":"Lame Sainte",
"Razor Shell":"Coquilame",
"Heat Crash":"Tacle Feu",
"Leaf Tornado":"Phytomixeur",
"Steamroller":"Bulldoboule",
"Cotton Guard":"Cotogarde",
"Night Daze":"Explonuit",
"Psystrike":"Frappe Psy",
"Tail Slap":"Plumo-Queue",
"Hurricane":"Vent Violent",
"Head Charge":"Peignée",
"Gear Grind":"Lancécrou",
"Searing Shot":"Incendie",
"Techno Blast":"Techno-Buster",
"Relic Song":"Chant Antique",
"Secret Sword":"Lame Ouinte",
"Glaciate":"Ère Glaciaire",
"Bolt Strike":"Charge Foudre",
"Blue Flare":"Flamme Bleue",
"Fiery Dance":"Danse du Feu",
"Freeze Shock":"Éclair Gelé",
"Ice Burn":"Feu Glacé",
"Snarl":"Aboiement",
"Icicle Crash":"Chute Glace",
"V-create":"Coup Victoire",
"Fusion Flare":"Flamme Croix",
"Fusion Bolt":"Éclair Croix",
"Flying Press":"Flying Press",
"Mat Block":"Tatamigaeshi",
"Belch":"Éructation",
"Rototiller":"Fertilisation",
"Sticky Web":"Toile Gluante",
"Fell Stinger":"Dard Mortel",
"Phantom Force":"Hantise",
"Trick-or-Treat":"Halloween",
"Noble Roar":"Râle Mâle",
"Ion Deluge":"DélugePlasma",
"Parabolic Charge":"Parabocharge",
"Forest's Curse":"Maléfice Sylvain",
"Petal Blizzard":"Tempête Florale",
"Freeze-Dry":"Lyophilisation",
"Disarming Voice":"Voix Enjôleuse",
"Parting Shot":"Dernier Mot",
"Topsy-Turvy":"Renversement",
"Draining Kiss":"Vampibaiser",
"Crafty Shield":"Vigilance",
"Flower Shield":"Garde Florale",
"Grassy Terrain":"Champ Herbu",
"Misty Terrain":"Champ Brumeux",
"Electrify":"Électrisation",
"Play Rough":"Câlinerie",
"Fairy Wind":"Vent Féérique",
"Moonblast":"Pouvoir Lunaire",
"Boomburst":"Bang Sonique",
"Fairy Lock":"Verrou Enchanté",
"King's Shield":"Bouclier Royal",
"Play Nice":"Camaraderie",
"Confide":"Confidence",
"Diamond Storm":"Orage Adamantin",
"Steam Eruption":"Jet de Vapeur",
"Hyperspace Hole":"TrouDimensionnel",
"Water Shuriken":"Sheauriken",
"Mystical Fire":"Feu Ensorcelé",
"Spiky Shield":"Pico-Défense",
"Aromatic Mist":"Brume Capiteuse",
"Eerie Impulse":"Ondes Étranges",
"Venom Drench":"Piège de Venin",
"Powder":"Nuée de Poudre",
"Geomancy":"Géo-Contrôle",
"Magnetic Flux":"Magné-Contrôle",
"Happy Hour":"Étrennes",
"Electric Terrain":"Champ Électrifié",
"Dazzling Gleam":"Éclat Magique",
"Celebrate":"Célébration",
"Hold Hands":"Mains Jointes",
"Baby-Doll Eyes":"Regard Touchant",
"Nuzzle":"Frotte-Frimousse",
"Hold Back":"Retenue",
"Infestation":"Harcèlement",
"Power-Up Punch":"Poing Boost",
"Oblivion Wing":"Mort-Ailes",
"Thousand Arrows":"Myria-Flèches",
"Thousand Waves":"Myria-Vagues",
"Land's Wrath":"Force Chtonienne",
"Light of Ruin":"Lumière du Néant",
"Origin Pulse":"Onde Originelle",
"Precipice Blades":"Lame Pangéenne",
"Dragon Ascent":"Draco Ascension",
"Hyperspace Fury":"Furie Dimension",
"Shore Up":"Amass'Sable",
"First Impression":"Escarmouche",
"Baneful Bunker":"Blockhaus",
"Spirit Shackle":"Tisse Ombre",
"Darkest Lariat":"Dark Lariat",
"Sparkling Aria":"Aria de l'Écume",
"Ice Hammer":"Marteau de Glace",
"Floral Healing":"Soin Floral",
"High Horsepower":"Cavalerie Lourde",
"Strength Sap":"Vol-Force",
"Solar Blade":"Lame Solaire",
"Leafage":"Feuillage",
"Spotlight":"Projecteur",
"Toxic Thread":"Fil Toxique",
"Laser Focus":"Affilage",
"Gear Up":"Engrenage",
"Throat Chop":"Exécu-Son",
"Pollen Puff":"Boule Pollen",
"Anchor Shot":"Ancrage",
  "Prevents the target from switching out. The target can still switch out if it is holding Shed Shell or uses Baton Pass, Flip Turn, Parting Shot, Teleport, U-turn, or Volt Switch. If the target leaves the field using Baton Pass, the replacement will remain trapped. The effect ends if the user leaves the field.":"Aucun adversaire qui subit cette capacité ne pourra s’enfuir du combat ou échanger sa place avec un allié. Ancrage inflige des dégâts à l'adversaire tout en l'empêchant de fuir le combat.",
  "Prevents the target from switching out.":"Empêche le pokémon d'être échangé au combat.",
  "Prevents the target from switching out. The target can still switch out if it is holding Shed Shell or uses Baton Pass, Parting Shot, U-turn, or Volt Switch. If the target leaves the field using Baton Pass, the replacement will remain trapped. The effect ends if the user leaves the field.":"Aucun adversaire qui subit cette capacité ne pourra s’enfuir du combat ou échanger sa place avec un allié. Ancrage inflige des dégâts à l'adversaire tout en l'empêchant de fuir le combat.",
"Psychic Terrain":"Champ Psychique",
"Lunge":"Furie-Bond",
"Fire Lash":"Fouet de Feu",
"Power Trip":"Arrogance",
"Burn Up":"Flamme Ultime",
"Speed Swap":"Permuvitesse",
"Smart Strike":"Estocorne",
"Purify":"Purification",
"Revelation Dance":"Danse Éveil",
"Core Enforcer":"Sanction Suprême",
"Trop Kick":"Botte Sucrette",
"Instruct":"Sommation",
"Beak Blast":"Bec-Canon",
"Clanging Scales":"Vibrécaille",
"Dragon Hammer":"Draco-Marteau",
"Brutal Swing":"Centrifugifle",
"Aurora Veil":"Voile Aurore",
"Shell Trap":"Carapiège",
"Fleur Cannon":"Canon Floral",
"Psychic Fangs":"Psycho-Croc",
"Stomping Tantrum":"Trépignement",
"Shadow Bone":"Os'Ombre",
"Accelerock":"Vif Roc",
  "No additional effect.":"Aucun effet supplémentaire.",
  "Usually goes first.":"Frappe en priorité.",
"Liquidation":"Aqua-Brèche",
"Prismatic Laser":"Laser Prisme",
"Spectral Thief":"Clepto-Mânes",
"Sunsteel Strike":"Choc Météore",
"Moongeist Beam":"Rayon Spectral",
"Tearful Look":"Larme à l'Œil",
"Zing Zap":"Électrikipik",
"Nature's Madness":"Ire de la Nature",
"Multi-Attack":"Coup Varia-Type",
"Mind Blown":"Caboche-Kaboum",
"Plasma Fists":"Plasma Punch",
"Photon Geyser":"Photo-Geyser",
"Breakneck Blitz":"Turbo-Charge Bulldozer",
"All-Out Pummeling":"Combo Hyper-Furie",
"Supersonic Skystrike":"Piqué Supersonique",
"Acid Downpour":"Déluge Causti-Toxique",
  "Power is equal to the base move's Z-Power.":"La puissance est égale à la puissance Z du mouvement de base.",
"Tectonic Rage":"Éruption Géo-Sismique",
"Continental Crush":"Apocalypse Gigalithique",
"Savage Spin-Out":"Cocon Fatal",
"Never-Ending Nightmare":"Appel des Ombres Éternelles",
"Corkscrew Crash":"Vrille Maximum",
"Inferno Overdrive":"Pyro-Explosion Cataclysmique",
"Hydro Vortex":"Super Tourbillon Abyssal",
"Bloom Doom":"Pétalexplosion Éblouissante",
"Gigavolt Havoc":"Fulguro-Lance Gigavolt",
"Shattered Psyche":"Psycho-Pulvérisation EX",
"Subzero Slammer":"Laser Cryogénique",
"Devastating Drake":"Chaos Draconique",
"Black Hole Eclipse":"Trou Noir des Ombres",
"Twinkle Tackle":"Impact Choupinova",
"Catastropika":"Pikachute Foudroyante",
"Sinister Arrow Raid":"Fureur des Plumes Spectrales",
"Malicious Moonsault":"Dark Body Press",
"Oceanic Operetta":"Symphonie des Ondines",
"Guardian of Alola":"Colère du Gardien d'Alola",
"Soul-Stealing 7-Star Strike":"Fauche-Âme des Sept Étoiles",
"Stoked Sparksurfer":"Électro-Surf Survolté",
"Pulverizing Pancake":"Gare au Ronflex",
"Extreme Evoboost":"Neuf pour Un",
"Genesis Supernova":"Supernova Originelle",
"10,000,000 Volt Thunderbolt":"Giga-Tonnerre",
  "Has a very high chance for a critical hit.":"A une très grande chance d'effectuer un coup critique.",
  "Very high critical hit ratio.":"Taux de critique élevé.",
"Light That Burns the Sky":"Apocalypsis Luminis",
"Searing Sunraze Smash":"Hélio-Choc Dévastateur",
"Menacing Moonraze Maelstrom":"Rayons Séléno-Explosifs",
"Let's Snuggle Forever":"Patati-Patattrape",
"Splintered Stormshards":"Hurlement des Roches-Lames",
"Clangorous Soulblaze":"Dracacophonie Flamboyante",

// Items Translation

"Repel":"Repousse",
"Super Repel":"Superepousse",
"Max Repel":"Max Repousse",
"Escape Rope":"Corde Sortie",
"Black Flute":"Flûte Noire·",
"White Flute":"Flûte Blanche",
"Shoal Salt":"Sel Trefonds",
"Shoal Shell":"CoquilleTréfonds",
"Red Shard":"Tesson Rouge",
"Blue Shard":"Tesson Bleu",
"Yellow Shard":"Tesson Jaune",
"Green Shard":"Tesson Vert",
"Exp. Share":"Multi Exp",
"Normal Box":"Coffre Normal",
"Gorgeous Box":"Coffre Luxe",
"Slowpoke Tail":"Queue Ramoloss",
"Honey":"Miel",
"Time Flute":"Flute du Temps",
"Poké Snack":"Pokésnack",
"Growth Mulch":"Fertipousse",
"Damp Mulch":"Fertihumide",
"Stable Mulch":"Fertistable",
"Gooey Mulch":"Fertiglu",
"Root Fossil":"Fossile Racine",
"Claw Fossil":"Fossile Griffe",
"Helix Fossil":"Fossile Nautile",
"Dome Fossil":"Fossile Dôme",
"Old Amber":"Vieil Ambre",
"Armor Fossil":"Fossile Armure",
"Skull Fossil":"Fossile Crâne",
"Odd Keystone":"Clé de Voûte",
"Cover Fossil":"Fossile Plaque",
"Plume Fossil":"Fossile Plume",
"Pass Orb":"Offrisphère",
"Ability Capsule":"Pilule Talent·",
"Rich Mulch":"Fertibondance",
"Surprise Mulch":"Fertistantané",
"Boost Mulch":"Fertibérance",
"Amaze Mulch":"Fertiprodige",
"Discount Coupon":"Bon Réduction",
"Strange Souvenir":"Bibelot Bizarre",
"Jaw Fossil":"Fossile Mâchoire",
"Sail Fossil":"Fossile Nageoire",
"Bottle Cap":"Capsule d'Argent",
"Gold Bottle Cap":"Capsule d'Or",
"Festival Ticket":"Festicket",
"Red Nectar":"Nectar Rouge",
"Yellow Nectar":"Nectar Jaune",
"Pink Nectar":"Nectar Rose",
"Purple Nectar":"Nectar Mauve",
"Sun Stone":"Pierre Soleil",
"Moon Stone":"Pierre Lune",
"Fire Stone":"Pierre Feu",
"Thunder Stone":"Pierre Foudre",
"Water Stone":"Pierre Eau",
"Leaf Stone":"Pierre Plante",
"Shiny Stone":"Pierre Éclat",
"Dusk Stone":"Pierre Nuit",
"Dawn Stone":"Pierre Aube",
"Ice Stone":"Pierre Glace",
"Tiny Mushroom":"Petit Champi",
"Big Mushroom":"Gros Champi",
"Pearl":"Perle",
"Big Pearl":"Grande Perle",
"Stardust":"Poussière Étoile",
"Star Piece":"Morceau d'Étoile",
"Gold Leaf":"Feuille D'Or",
"Silver Leaf":"Feuille Arg.",
"Brick Piece":"Morc. Brique",
"Nugget":"Pépite",
"Heart Scale":"Écaille Cœur",
"Rare Bone":"Os Rare",
"Pretty Wing":"Jolie Aile",
"Balm Mushroom":"Champi Suave",
"Big Nugget":"Maxi Pépite",
"Pearl String":"Perle Triple",
"Comet Shard":"Morceau Comète",
"Relic Copper":"Vieux Sou",
"Relic Silver":"Vieil Écu",
"Relic Gold":"Vieux Ducat",
"Relic Vase":"Vieux Vase",
"Relic Band":"Vieux Bijou",
"Relic Statue":"Vieux Santon",
"Relic Crown":"Vieux Tortil",
"Bright Powder":"Poudre Claire",
"Quick Claw":"Vive Griffe",
"King's Rock":"Roche Royale",
"Silver Powder":"Poudre Argentée",
"Amulet Coin":"Pièce Rune",
"Cleanse Tag":"Rune Purifiante",
"Smoke Ball":"Boule Fumée",
"Everstone":"Pierre Stase",
"Focus Band":"Bandeau",
"Lucky Egg":"Œuf Chance",
"Scope Lens":"Lentilscope",
"Metal Coat":"Peau Metal",
"Leftovers":"Restes",
"Dragon Scale":"Écaille Draco",
"Light Ball":"Ballelumiere",
"Soft Sand":"Sable Doux",
"Hard Stone":"Pierre Dure",
"Miracle Seed":"Grain Miracle",
"Black Glasses":"Lunettes Noires",
"Black Belt":"Ceinture Noire",
"Magnet":"Aimant",
"Mystic Water":"Eau Mystique",
"Sharp Beak":"Bec Pointu",
"Poison Barb":"Pic Venin",
"Never-Melt Ice":"Glace Éternelle",
"Spell Tag":"Rune Sort",
"Twisted Spoon":"Cuiller Tordue",
"Charcoal":"Charbon",
"Dragon Fang":"Croc Dragon",
"Pink Bow":"Ruban Rose",
"Polkadot Bow":"Ruban à Pois",
"Up-Grade":"Améliorator",
"Lucky Punch":"Poing Chance",
"Metal Powder":"Poudre Metal",
"Thick Club":"Masse Os",
"Stick":"Baton",
"Berserk Gene":"ADN Berzerk",
"White Herb":"Herbe Blanche",
"Macho Brace":"Bracelet Macho",
"Soothe Bell":"Grelot Zen",
"Mental Herb":"Herbe Mental",
"Choice Band":"Bandeau Choix",
"Soul Dew":"Rosée Âme",
"Deep Sea Tooth":"Dent Océan",
"Deep Sea Scale":"Écaille Océan",
"Silk Scarf":"Mouchoir Soie",
"Shell Bell":"Grelot Coque",
"Sea Incense":"Encens Mer",
"Lax Incense":"Encens Doux",
"Red Scarf":"Foul. Rouge",
"Blue Scarf":"Foul. Bleu",
"Pink Scarf":"Foul. Rose",
"Green Scarf":"Foul. Vert",
"Yellow Scarf":"Foul. Jaune",
"Red Orb":"Gemme Rouge",
"Blue Orb":"Gemme Bleue",
"Flame Plate":"Plaque Flam",
"Splash Plate":"Plaque Hydro",
"Zap Plate":"Plaque Volt",
"Meadow Plate":"Plaque Herbe",
"Icicle Plate":"Plaque Glace",
"Fist Plate":"Plaque Poing",
"Toxic Plate":"Plaque Toxic",
"Earth Plate":"Plaque Terre",
"Sky Plate":"Plaque Ciel",
"Mind Plate":"Plaque Esprit",
"Insect Plate":"Plaquinsect",
"Stone Plate":"Plaque Roc",
"Spooky Plate":"Plaque Fantô",
"Draco Plate":"Plaque Draco",
"Dread Plate":"Plaque Ombre",
"Iron Plate":"Plaque Fer",
"Odd Incense":"Encens Bizarre",
"Rock Incense":"Encens Roc",
"Full Incense":"Encens Plein",
"Wave Incense":"Encens Vague",
"Rose Incense":"Encens Fleur",
"Luck Incense":"Encens Veine",
"Pure Incense":"Encens Pur",
"Protector":"Protecteur",
"Electirizer":"Électiriseur",
"Magmarizer":"Magmariseur",
"Dubious Disc":"CD Douteux",
"Reaper Cloth":"Tissu Fauche",
"Razor Claw":"Griffe Rasoir",
"Razor Fang":"Croc Rasoir",
"Oval Stone":"Pierre Ovale",
"Adamant Orb":"Orbe Adamant",
"Lustrous Orb":"Orbe Perlé",
"Griseous Orb":"Orbe Platiné",
"Wide Lens":"Loupe",
"Muscle Band":"Bandeau Muscle",
"Wise Glasses":"Lunettes Sages",
"Expert Belt":"Ceinture Pro",
"Light Clay":"Lumargile",
"Life Orb":"Orbe Vie",
"Power Herb":"Herbe Pouvoir",
"Toxic Orb":"Orbe Toxique",
"Flame Orb":"Orbe Flamme",
"Quick Powder":"Poudre Vite",
"Focus Sash":"Ceinture Force",
"Zoom Lens":"Lentille Zoom",
"Metronome":"Métronome",
"Iron Ball":"Balle Fer",
"Lagging Tail":"Ralentiqueue·",
"Destiny Knot":"Nœud Destin",
"Black Sludge":"Boue Noire",
"Icy Rock":"Roche Glace",
"Smooth Rock":"Roche Lisse",
"Heat Rock":"Roche Chaude",
"Damp Rock":"Roche Humide",
"Grip Claw":"Accro Griffe",
"Choice Scarf":"Mouchoir Choix",
"Sticky Barb":"Piquants",
"Power Bracer":"Poignée Pouvoir",
"Power Belt":"Ceinture Pouvoir",
"Power Lens":"Lentille Pouvoir",
"Power Band":"Bandeau Pouvoir",
"Power Anklet":"Chaîne Pouvoir",
"Power Weight":"Poids Pouvoir",
"Shed Shell":"Carapace Mue",
"Big Root":"Grosse Racine",
"Choice Specs":"Lunettes Choix",
"Douse Drive":"Module Aqua",
"Shock Drive":"Module Choc",
"Burn Drive":"Module Pyro",
"Chill Drive":"Module Cryo",
"Prism Scale":"Bel'Écaille",
"Eviolite":"Évoluroc",
"Float Stone":"Pierrallégée",
"Rocky Helmet":"Casque Brut",
"Air Balloon":"Ballon",
"Red Card":"Carton Rouge",
"Ring Target":"Point de Mire",
"Binding Band":"Bande Étreinte",
"Absorb Bulb":"Bulbe",
"Cell Battery":"Pile",
"Eject Button":"Bouton Fuite",
"Fire Gem":"Joyau Feu",
"Water Gem":"Joyau Eau",
"Electric Gem":"Joyau Électr",
"Grass Gem":"Joyau Plante",
"Ice Gem":"Joyau Glace",
"Fighting Gem":"Joyau Combat",
"Poison Gem":"Joyau Poison",
"Ground Gem":"Joyau Sol",
"Flying Gem":"Joyau Vol",
"Psychic Gem":"Joyau Psy",
"Bug Gem":"Joyau Insecte",
"Rock Gem":"Joyau Roche",
"Ghost Gem":"Joyau Spectre",
"Dragon Gem":"Joyau Dragon",
"Dark Gem":"Joyau Ténèbres",
"Steel Gem":"Joyau Acier",
"Normal Gem":"Joyau Normal",
"Fairy Gem":"Joyau Fée",
"Weakness Policy":"Vulné-Assurance",
"Assault Vest":"Veste de Combat",
"Pixie Plate":"Plaque Pixie",
"Whipped Dream":"Chantibonbon",
"Sachet":"Sachet Senteur",
"Luminous Moss":"Lichen Lumineux",
"Snowball":"Boule de Neige",
"Safety Goggles":"Lunettes Filtre",
"Gengarite":"Ectoplasmite",
"Gardevoirite":"Gardevoirite",
"Ampharosite":"Pharampite",
"Venusaurite":"Florizarrite",
"Charizardite X":"Dracaufite X",
"Blastoisinite":"Tortankite",
"Mewtwonite X":"Mewtwoïte X",
"Mewtwonite Y":"Mewtwoïte Y",
"Blazikenite":"Braségalite",
"Medichamite":"Charminite",
"Houndoominite":"Démolossite",
"Aggronite":"Galekingite",
"Banettite":"Branettite",
"Tyranitarite":"Tyranocivite",
"Scizorite":"Cizayoxite",
"Pinsirite":"Scarabruite",
"Aerodactylite":"Ptéraïte",
"Lucarionite":"Lucarite",
"Abomasite":"Blizzarite",
"Kangaskhanite":"Kangourexite",
"Gyaradosite":"Léviatorite",
"Absolite":"Absolite",
"Charizardite Y":"Dracaufite Y",
"Alakazite":"Alakazamite",
"Heracronite":"Scarhinoïte",
"Mawilite":"Mysdibulite",
"Manectite":"Élecsprintite",
"Garchompite":"Carchacrokite",
"Latiasite":"Latiasite",
"Latiosite":"Latiosite",
"Swampertite":"Laggronite",
"Sceptilite":"Jungkite",
"Sablenite":"Ténéfixite",
"Altarianite":"Altarite",
"Galladite":"Gallamite",
"Audinite":"Nanméouïte",
"Metagrossite":"Métalossite",
"Sharpedonite":"Sharpedite",
"Slowbronite":"Flagadossite",
"Steelixite":"Steelixite",
"Pidgeotite":"Roucarnagite",
"Glalitite":"Oniglalite",
"Diancite":"Diancite",
"Cameruptite":"Caméruptite",
"Lopunnite":"Lockpinite",
"Salamencite":"Drattakite",
"Beedrillite":"Dardargnite",
"Normalium Z":"Normazélite",
"Firium Z":"Pyrozélite",
"Waterium Z":"Aquazélite",
"Electrium Z":"Voltazélite",
"Grassium Z":"Florazélite",
"Icium Z":"Cryozélite",
"Fightinium Z":"Combazélite",
"Poisonium Z":"Toxizélite",
"Groundium Z":"Terrazélite",
"Flyinium Z":"Aérozélite",
"Psychium Z":"Psychézélite",
"Buginium Z":"Insectozélite",
"Rockium Z":"Rocazélite",
"Ghostium Z":"Spectrozélite",
"Dragonium Z":"Dracozélite",
"Darkinium Z":"Ténébrozélite",
"Steelium Z":"Métallozélite",
"Fairium Z":"Nymphézélite",
"Pikanium Z":"Pikazélite",
"Decidium Z":"Archézélite",
"Incinium Z":"Félinozélite",
"Primarium Z":"Oratozélite",
"Tapunium Z":"Tokozélite",
"Marshadium Z":"Marshadozélite",
"Aloraichium Z":"Aloraïzélite",
"Snorlium Z":"Ronflézélite",
"Eevium Z":"Évolizélite",
"Mewnium Z":"Mewzélite",
"Pikashunium Z":"Pikachazélite",
"Adrenaline Orb":"Orbe Frousse",
"Terrain Extender":"Champ'Duit",
"Protective Pads":"Pare-Effet",
"Electric Seed":"Graine Électrik",
"Psychic Seed":"Graine Psychique",
"Misty Seed":"Graine Brume",
"Grassy Seed":"Graine Herbe",
"Fighting Memory":"ROM Combat",
"Flying Memory":"ROM Vol",
"Poison Memory":"ROM Poison",
"Ground Memory":"ROM Sol",
"Rock Memory":"ROM Roche",
"Bug Memory":"ROM Insecte",
"Ghost Memory":"ROM Spectre",
"Steel Memory":"ROM Acier",
"Fire Memory":"ROM Feu",
"Water Memory":"ROM Eau",
"Grass Memory":"ROM Plante",
"Electric Memory":"ROM Électrik",
"Psychic Memory":"ROM Psy",
"Ice Memory":"ROM Glace",
"Dragon Memory":"ROM Dragon",
"Dark Memory":"ROM Ténèbres",
"Fairy Memory":"ROM Fée",
"Solganium Z":"Solgazélite",
"Lunalium Z":"Lunazélite",
"Ultranecrozium Z":"Ultranécrozélite",
"Mimikium Z":"Mimiquizélite",
"Lycanium Z":"Lougarozélite",
"Kommonium Z":"Ékaïzélite",
"Roto Hatch":"Moti-Couveuse",
"Roto Bargain":"Moti-Promo",
"Roto Prize Money":"Moti-Magot",
"Roto Exp. Points":"Molti-Exp",
"Roto Friendship":"Moti-Cœur",
"Roto Encounter":"Moti-Appât",
"Roto Stealth":"Moti-Camouflage",
"Roto HP Restore":"Moti-Récup' PV",
"Roto PP Restore":"Moti-Récup' PP",
"Roto Boost":"Moti-Soutien",
"Roto Catch":"Moti-Capture",
"Poké Ball":"Poké Ball",
"Great Ball":"Super Ball",
"Ultra Ball":"Hyper Ball",
"Master Ball":"Master Ball",
"Safari Ball":"Safari Ball",
"Heavy Ball":"Masse Ball",
"Level Ball":"Niveau Ball",
"Lure Ball":"Appat Ball",
"Fast Ball":"Speed Ball",
"Friend Ball":"Copain Ball",
"Moon Ball":"Lune Ball",
"Love Ball":"Love Ball",
"Sport Ball":"Compét'Ball",
"Net Ball":"Filet Ball",
"Dive Ball":"Scuba Ball",
"Nest Ball":"Faiblo Ball",
"Repeat Ball":"Bis Ball",
"Timer Ball":"Chrono Ball",
"Luxury Ball":"Luxe Ball",
"Premier Ball":"Honor Ball",
"Dusk Ball":"Sombre Ball",
"Heal Ball":"Soin Ball",
"Quick Ball":"Rapide Ball",
"Cherish Ball":"Mémoire Ball",
"Park Ball":"Parc Ball",
"Dream Ball":"Rêve Ball",
"Beast Ball":"Ultra Ball",
"Flower Mail":"Lettre Fleur",
"Surf Mail":"Lettre Surf",
"Litebluemail":"LetrBleuCiel",
"Portraitmail":"LetrPortrait",
"Lovely Mail":"LetrCharm.",
"Eon Mail":"Lettre Evoli",
"Morph Mail":"Lettre Morph",
"Bluesky Mail":"LetrCielBleu",
"Music Mail":"Lettre Musique",
"Mirage Mail":"Lettre Mirage",
"Orange Mail":"Lettre Oranj",
"Harbor Mail":"Lettre Port",
"Glitter Mail":"Lettre Brill",
"Mech Mail":"Lettre Meca",
"Wood Mail":"Lettre Bois",
"Wave Mail":"Lettre Vague",
"Bead Mail":"Lettre Bulle",
"Shadow Mail":"Lettre Ombre",
"Tropic Mail":"Lettre Tropi",
"Dream Mail":"Lettre Songe",
"Fab Mail":"Lettre Cool",
"Retro Mail":"Lettre Retro",
"Grass Mail":"Lettre Herbe",
"Flame Mail":"Lettre Feu",
"Bubble Mail":"Lettre Mer",
"Bloom Mail":"Lett. Pétale",
"Tunnel Mail":"Lettre Mine",
"Steel Mail":"Lettre Acier",
"Heart Mail":"Lettre Coeur",
"Snow Mail":"Lettre Neige",
"Space Mail":"Lettre Cosmo",
"Air Mail":"Lettre Avion",
"Mosaic Mail":"Lettremosaik",
"Brick Mail":"Lettre Brik",
"Greet Mail":"Lettre Salut",
"Favored Mail":"Lettre Fan",
"RSVP Mail":"Lettre Invit",
"Thanks Mail":"Lettre Merci",
"Inquiry Mail":"Let. Demande",
"Like Mail":"Lettre Avis",
"Reply Mail":"Let. Réponse",
"BridgeMail S":"Lettre PontS",
"BridgeMail D":"Lettre PontY",
"BridgeMail T":"Lettre PontF",
"BridgeMail V":"Lettre PontH",
"BridgeMail M":"Lettre PontI",
"Guard Spec.":"Defense Spec",
"Dire Hit":"Muscle +",
"X Attack":"Attaque +",
"X Defense":"Défense +",
"X Speed":"Vitesse +",
"X Accuracy":"Precision +",
"X Sp. Atk":"Special +",
"X Sp. Def":"Def. Spé. +",
"Poké Doll":"Poképoupée",
"Fluffy Tail":"Queue Skitty",
"Blue Flute":"Flûte Bleue",
"Yellow Flute":"Flûte Jaune",
"Red Flute":"Flûte Rouge",
"Poké Toy":"Poképlumet",
"Ability Urge":"Appel CapSpé·",
"Item Drop":"Jette Objet",
"Item Urge":"Appel Objet",
"Reset Urge":"Réamorçage",
"Potion":"Potion",
"Antidote":"Antidote",
"Burn Heal":"Anti-Brûle",
"Ice Heal":"Antigel",
"Awakening":"Reveil",
"Paralyze Heal":"Anti-Para",
"Full Restore":"Guerison",
"Max Potion":"Potion Max",
"Hyper Potion":"Hyper Potion",
"Super Potion":"Super Potion",
"Full Heal":"Total Soin",
"Revive":"Rappel",
"Max Revive":"Rappel Max",
"Fresh Water":"Eau Fraiche",
"Soda Pop":"Soda Cool",
"Lemonade":"Limonade",
"Moomoo Milk":"Lait Meumeu",
"Ether":"Huile",
"Max Ether":"Huile Max",
"Elixir":"Elixir",
"Max Elixir":"Max Elixir",
"Energy Powder":"Poudre Énergie",
"Energy Root":"Racine Énergie",
"Heal Powder":"Poudre Soin",
"Revival Herb":"Herbe Rappel",
"Sacred Ash":"Cendres Sacrées",
"Rage Candy Bar":"Bonbon Rage",
"Lava Cookie":"Lava Cookie",
"Berry Juice":"Jus De Baie",
"HP Up":"PV Plus",
"Protein":"Proteine",
"Iron":"Fer",
"Carbos":"Carbone",
"Calcium":"Calcium",
"Rare Candy":"Super Bonbon",
"PP Up":"PP Plus",
"Zinc":"Zinc",
"PP Max":"PP Max",
"Old Gateau":"Vieux Gâteau",
"Sweet Heart":"Chococœur",
"Health Wing":"Aile Santé",
"Muscle Wing":"Aile Force",
"Resist Wing":"Aile Armure",
"Genius Wing":"Aile Esprit",
"Clever Wing":"Aile Mental",
"Swift Wing":"Aile Sprint",
"Casteliacone":"Glace Volute",
"Lumiose Galette":"Galette Illumis",
"Shalour Sable":"Sablé Yantreizh",
"Big Malasada":"Malasada Maxi",
"HM":"CS",
"TM":"CT",
"Berry":"Baie",
"Gold Berry":"Baie Doree",
"PSNCureBerry":"Baie Antidot·",
"PRZCureBerry":"Baie AntiPAR",
"Mint Berry":"Baie Menthe",
"Burnt Berry":"Baie Brulure",
"Ice Berry":"Baie Gel",
"Bitter Berry":"Baie Amere",
"MysteryBerry":"Baie Mystere",
"MiracleBerry":"Baie Miracle",
"Cheri Berry":"Baie Ceriz",
"Chesto Berry":"Baie Maron",
"Pecha Berry":"Baie Pecha",
"Rawst Berry":"Baie Fraive",
"Aspear Berry":"Baie Willia",
"Leppa Berry":"Baie Mepo",
"Oran Berry":"Baie Oran",
"Persim Berry":"Baie Kika",
"Lum Berry":"Baie Prine",
"Sitrus Berry":"Baie Sitrus",
"Figy Berry":"Baie Figuy",
"Wiki Berry":"Baie Wiki",
"Mago Berry":"Baie Mago",
"Aguav Berry":"Baie Gowav",
"Iapapa Berry":"Baie Papaya",
"Razz Berry":"Baie Framby",
"Bluk Berry":"Baie Remu",
"Nanab Berry":"Baie Nanab",
"Wepear Berry":"Baie Repoi",
"Pinap Berry":"Baie Nanana",
"Pomeg Berry":"Baie Grena",
"Kelpsy Berry":"Baie Alga",
"Qualot Berry":"Baie Qualot",
"Hondew Berry":"Baie Lonme",
"Grepa Berry":"Baie Resin",
"Tamato Berry":"Baie Tamato",
"Cornn Berry":"Baie Siam",
"Magost Berry":"Baie Mangou",
"Rabuta Berry":"Baie Rabuta",
"Nomel Berry":"Baie Tronci",
"Spelon Berry":"Baie Kiwan",
"Pamtre Berry":"Baie Palma",
"Watmel Berry":"Baie Stekpa",
"Durin Berry":"Baie Durin",
"Belue Berry":"Baie Myrte",
"Liechi Berry":"Baie Lichii",
"Ganlon Berry":"Baie Lingan",
"Salac Berry":"Baie Sailak",
"Petaya Berry":"Baie Pitaye",
"Apicot Berry":"Baie Abriko",
"Lansat Berry":"Baie Lansat",
"Starf Berry":"Baie Frista",
"Enigma Berry":"Baie Enigma",
"Occa Berry":"Baie Chocco",
"Passho Berry":"Baie Pocpoc",
"Wacan Berry":"Baie Parma",
"Rindo Berry":"Baie Ratam",
"Yache Berry":"Baie Nanone",
"Chople Berry":"Baie Pomroz",
"Kebia Berry":"Baie Kébia",
"Shuca Berry":"Baie Jouca",
"Coba Berry":"Baie Cobaba",
"Payapa Berry":"Baie Yapap",
"Tanga Berry":"Baie Panga",
"Charti Berry":"Baie Charti",
"Kasib Berry":"Baie Sédra",
"Haban Berry":"Baie Fraigo",
"Colbur Berry":"Baie Lampou",
"Babiri Berry":"Baie Babiri",
"Chilan Berry":"Baie Zalis",
"Micle Berry":"Baie Micle",
"Custap Berry":"Baie Chérim",
"Jaboca Berry":"Baie Jacoba",
"Rowap Berry":"Baie Pommo",
"Roseli Berry":"Baie Selro",
"Kee Berry":"Baie Éka",
"Maranga Berry":"Baie Rangma",
"Coin Case":"Boite Jetons",
"Itemfinder":"Cherch'Objet",
"Old Rod":"Canne",
"Good Rod":"Super Canne",
"Super Rod":"Mega Canne",
"S.S. Ticket":"Passe Bateau",
"Oak's Parcel":"Colis Chen",
"Poké Flute":"Pokéflute",
"Secret Key":"Clé Secrète",
"Bike Voucher":"Bon Commande",
"Gold Teeth":"Dent D'or",
"Card Key":"Carte ",
"Lift Key":"Cle ",
"Silph Scope":"Scope Sylphe",
"Bicycle":"Bicyclette",
"Town Map":"Carte",
"GS Ball":"GS Ball",
"Egg Ticket":"Ticket Oeuf",
"Clear Bell":"Glas Transparent",
"Blue Card":"Carte Bleue",
"Squirt Bottle":"Carapuce à O",
"Red Scale":"Écaillerouge",
"Lost Item":"Poupée perdue",
"Pass":"Passe train",
"Machine Part":"Partie de Machine",
"Silver Wing":"Argent'Aile",
"Rainbow Wing":"Arcenci'Aile",
"Mystery Egg":"Œuf Mystère",
"Secret Potion":"Potionsecret",
"Contest Pass":"Passe Concours ",
"Mach Bike":"Vélo de Course",
"Acro Bike":"Vélo Cross",
"Wailmer Pail":"Wailmerrosoir",
"Devon Parts":"Pack Devon",
"Soot Sack":"Sac à Suie",
"Basement Key":"Clé Sous-Sol",
"Pokéblock Case":"Boite Pokéblocs",
"Letter":"Lettre à Pierre",
"Eon Ticket":"Passe Éon",
"Scanner":"Scanner",
"Go-Goggles":"Lunettes Sable",
"Meteorite":"Météorite",
"Key to Room 1":"Clé salle 1",
"Key to Room 2":"Clé salle 2",
"Key to Room 4":"Clé salle 4",
"Key to Room 6":"Clé salle 6",
"Storage Key":"Clé Stockage",
"Devon Scope":"Devon Scope",
"Vs. Seeker":"Cherche VS",
"Fame Checker":"Memorydex",
"TM Case":"Boite CT",
"Berry Pouch":"Sac A Baies",
"Teachy TV":"TV ABC",
"Tri-Pass":"Tri-Pass",
"Rainbow Pass":"Passe Prisme",
"Tea":"The",
"MysticTicket":"Ticketmystik",
"AuroraTicket":"Ticketaurora",
"Powder Jar":"Pot Poudre",
"Ruby":"Rubis",
"Sapphire":"Saphir",
"Magma Emblem":"Emblème Magma",
"Old Sea Map":"Vieille Carte",
"Jail Key":"Clé de la prison",
"Elevator Key":"Cle Ascens.",
"Small Tablet":"Ardoise",
"F-Disk":"Disque A",
"R-Disk":"Disque D",
"L-Disk":"Disque G",
"D-Disk":"Disque B",
"U-Disk":"Disque H",
"Subway Key":"Clé de contact",
"Maingate Key":"Clé labo",
"Card Key":"Clé magnétique",
"Down St. Key":"Clé du sous-sol",
"DNA Sample":"Échantillon ADN",
"Data ROM":"Disque-ROM",
"Steel Teeth":"Dentier d'acier",
"Gear":"Roue dentée",
"Red ID Badge":"Passe rouge",
"Grn ID Badge":"Passe vert",
"Blu ID Badge":"Passe bleu",
"Ylw ID Badge":"Passe jaune",
"Ein File S":"Dossier Teck O",
"Ein File H":"Dossier Teck H",
"Ein File C":"Dossier Teck C",
"Ein File P":"Dossier Teck P",
"Cologne Case":"Boite a Parfums",
"Powerup Part":"Amplificateur",
"Ein File F":"Dossier Teck F",
"Machine Part":"Piece Meca.",
"ID Card":"Badge",
"Music Disc":"CD Musique",
"Krane Memo 1":"Memo Syrus 1",
"Krane Memo 2":"Memo Syrus 2",
"System Lever":"Levier",
"Sun Shard":"Eclat Soleil",
"Moon Shard":"Eclat Lune",
"Disc Case":"Boite Holog.",
"Krane Memo 3":"Memo Syrus 3",
"Krane Memo 4":"Memo Syrus 4",
"Krane Memo 5":"Memo Syrus 5",
"Mayor's Note":"Lettre Maire",
"Gonzap's Key":"Cle Helgonza",
"Miror Radar":"Radar Disco",
"Bonsly Card":"Carte Manzai",
"Bonsly Photo":"Photo Manzai",
"Voice Case 1":"Boite Cri 1",
"Voice Case 2":"Boite Cri 2",
"Voice Case 3":"Boite Cri 3",
"Voice Case 4":"Boite Cri 4",
"Voice Case 5":"Boite Cri 5",
"Cry Analyzer":"Decodeur Cri",
"Explorer Kit":"Explorakit",
"Loot Sack":"Sac Butin",
"Rule Book":"Livre Règles",
"Poké Radar":"Poké Radar",
"Point Card":"Carte Points",
"Journal":"Journal",
"Seal Case":"Boîte Sceaux·",
"Fashion Case":"Coffret Mode",
"Seal Bag":"Sac Sceaux",
"Pal Pad":"Registre Ami",
"Works Key":"Clé Centrale",
"Old Charm":"Vieux Grigri",
"Galactic Key":"Clé Galaxie",
"Red Chain":"Chaîne Rouge",
"Sprayduck":"Kwakarrosoir",
"Poffin Case":"Boîte Poffin",
"Suite Key":"Clé Chambre",
"Oak's Letter":"Lettre Chen",
"Lunar Wing":"Lun'Aile",
"Member Card":"Carte Membre·",
"Azure Flute":"Flûte Azur",
"Magma Stone":"Pierre Magma",
"Parcel":"Colis",
"Coupon 1":"Bon 1",
"Coupon 2":"Bon 2",
"Coupon 3":"Bon 3",
"Vs. Recorder":"Magnéto VS",
"Gracidea":"Gracidée",
"Apricorn Box":"Bte Noigrume",
"Unown Report":"Carnet Zarbi",
"Berry Pots":"Plante Baies",
"Dowsing Machine":"Cherch'Objet",
"Photo Album":"Album Photo",
"GB Sounds":"Lecteur GB",
"Tidal Bell":"Glas tempête",
"Data Card":"Carte Mémo",
"Jade Orb":"Orbe Vert",
"Lock Capsule":"Capsule Anti-vol",
"Enigma Stone":"Mystécristal",
"Liberty Pass":"Passe Liberté",
"Prop Case":"Boîte Parure",
"Dragon Skull":"Crâne Dragon",
"Light Stone":"Galet Blanc",
"Dark Stone":"Galet Noir",
"Xtransceiver":"Vokit",
"God Stone·ゴッドストーン":"—",
"Gram 1":"Courier 1",
"Gram 2":"Courier 2",
"Gram 3":"Courier 3",
"Medal Box":"B. Médailles",
"DNA Splicers":"Pointeau ADN",
"Permit":"Permis",
"Oval Charm":"Charme Ovale",
"Shiny Charm":"Charme Chroma",
"Plasma Card":"Carte Plasma",
"Grubby Hanky":"MouchoirSale",
"Colress MCHN":"Nikodule",
"Dropped Item":"Objet Trouvé",
"Reveal Glass":"Miroir Sacré",
"Holo Caster":"Holokit",
"Prof's Letter":"Lettre du Prof",
"Roller Skates":"Rollers",
"Sprinklotad":"Nénurrosoir",
"Power Plant Pass":"Passe Centrale",
"Mega Ring":"Méga-Anneau",
"Intriguing Stone":"Pierre Insolite",
"Elevator Key":"Clé Ascenseur",
"TMV Pass":"Passe TMV",
"Honor of Kalos":"Insigne de Kalos",
"Adventure Rules":"ABC Aventure",
"Lens Case":"Boîte Lentilles",
"Looker Ticket":"Ticket Beladonis",
"Mega Charm":"Méga-Charme",
"Pokéblock Kit":"Kit Pokébloc",
"Devon Scuba Gear":"Plongeur Devon",
"Contest Costume":"Costume/Robe Live",
"Magma Suit":"Scaph. Magma",
"Aqua Suit":"Scaphandre Aqua",
"Pair of Tickets":"Ticket Duo",
"Mega Bracelet":"Méga-Bracelet",
"Prison Bottle":"Vase Scellé",
"Mega Cuff":"Méga-Manchette",
"Meteorite Shard":"Éclat Météorite",
"Eon Flute":"Flûte Éon",
"Makeup Bag":"Trousse Beauté",
"Key Stone":"Gemme Sésame",
"Z-Ring":"Bracelet Z",
"Forage Bag":"Sac Ingrédients",
"Fishing Rod":"Canne à Pêche",
"Professor's Mask":"Masque du Prof",
"Sparkling Stone":"Gemme Lumière",
"Zygarde Cube":"Boîte Zygarde",
"Ride Pager":"Appel-Monture",
"Sun Flute":"Flûte du Soleil",
"Moon Flute":"Flûte de la Lune",
"Enigmatic Card":"Message Mystère",
"Z-Power Ring":"Super Bracelet Z",
"Pink Petal":"Pétale Rose",
"Orange Petal":"Pétale Orange",
"Blue Petal":"Pétale Bleu",
"Red Petal":"Pétale Rouge",
"Green Petal":"Pétale Vert",
"Yellow Petal":"Pétale Jaune",
"Purple Petal":"Pétale Violet",
"Rainbow Flower":"Fleur 7 Couleurs",
"Surge Badge":"Fulguro-Badge",
"N-Solarizer":"Necrosol",
"N-Lunarizer":"Necroluna",
"Ilima's Normalium Z":"Cristal Z Althéo",
"Left Poké Ball":"Poké Ball donnée",
"Red Apricorn":"Noigrume ",
"Blue Apricorn":"Noigrume ",
"Yellow Apricorn":"Noigrume ",
"Green Apricorn":"Noigrume ",
"Pink Apricorn":"Noigrume ",
"White Apricorn":"Noigrume ",
"Black Apricorn":"Noigrume ",
"Joy Scent":"P. Doux",
"Excite Scent":"P. Tonifiant",
"Vivid Scent":"P. Palpitant",

// Extra PM Names

"-Rainy":"-Pluie",
"-Snowy":"-Neige",
"-Sunny":"-Soleil",
"-Attack":"-Attaque",
"-Defense":"-Défense",
"-Speed":"-Vitesse",
"-Fan":"-Hélice",
"-Wash":"-Lavage",
"-Mow":"-Tonte",
"-Heat":"-Chaleur",
"-Frost":"-Froid",
"-Origin":"-Origine",
"-Sky":"-Ciel",
"-Bug":"-Bug",
"-Dark":"-Sombre",
"-Dragon":"-Dragon",
"-Electric":"-Électrique",
"-Fairy":"-Fée",
"-Fighting":"-Combat",
"-Fire":"-Feu",
"-Flying":"-Vol",
"-Ghost":"-Spectre",
"-Grass":"-Plante",
"-Ground":"-Sol",
"-Ice":"-Glace",
"-Poison":"-Poison",
"-Psychic":"-Psy",
"-Rock":"-Roche",
"-Steel":"-Acier",
"-Water":"-Eau",
"-Zen":"-Zen",
"-Resolute":"-Résolu",
"-Pirouette":"-Pirouette",
"-Burn":"-Brûlant",
"-Chill":"-Relax",
"-Douse":"-Mouillé",
"-Shock":"-Shock",
"-Ash":"-Cendre",
"-Eternal":"-Éternel",
"-Large":"-Grand",
"-Small":"-Petit",
"-Super":"-Super",
"-Unbound":"-Unbound",
"-Busted":"-Busted",
"-Primal":"-Primal",
"-Sandy":"-Sable",
"-Trash":"-Déchet",
"-Sunshine":"-Rayon",
"-Blue-Striped":"-Rayé-Bleu",
"-Therian":"-Therian",
"-Black":"-Noir",
"-White":"-Blanc",
"-Pa'u":"-Pa'u",
"-Pom-Pom":"-Pom-Pom",
"-Sensu":"-Sensu",
"-Midnight":"-Minuit",
"-School":"-École",
"-Alola":"-Alola",
"-Hoenn":"-Hoenn",
"-Kalos":"-Kalos",
"-Original":"-Original",
"-Sinnoh":"-Sinnoh",
"-Unova":"-Unova",
"-Dusk":"-Crépuscule",
"-Dawn-Wings":"-Dawn-Wings",
"-Dusk-Mane":"-Dusk-Mane",
"-Ultra":"-Ultra",
"-Totem":"-Totem",

// Item Desc

// Move Desc



//battle.js start

"The sunlight turned harsh!":"Le soleil tape fort !",
"s Drought intensified the sun's rays!":" : La capacité Sécheresse intensifie les rayons du soleil !",
"The sunlight faded.":"Le soleil redevient normal.",
"The sunlight turned extremely harsh!":"Le soleil devient très fort !",
"The harsh sunlight faded.":"Le soleil redevient normal.",
"It started to rain!":"La pluie commence à tomber !",
"s Drizzle made it rain!":" : La capacité Crachin fait commencer la pluie !",
"The rain stopped.":"La pluie s'arrête.",
"A heavy rain began to fall!":"Une pluie très forte vient de commencer !",
"The heavy rain has lifted!":"La pluie s'arrête.",
"A sandstorm kicked up!":"Une tempête de sable commence !",
"s Sand Stream whipped up a sandstorm!":" : La capacité Sable Volant a créé une tempête !",
"The sandstorm is raging.":"La tempête fait rage !",
"The sandstorm subsided.":"La tempête se calme.",
"It started to hail!":"De la grèle commence à tomber !",
"s Snow Warning whipped up a hailstorm!":" : La capacité Alerte Neige amène de la grèle !",
"The hail is crashing down.":"La grèle se calme.",
"The hail stopped.":"La grèle s'est arrêtée.",
"Mysterious strong winds are protecting Flying-type Pok&eacute;mon!":"Des vents mystérieux protègent les Pokémon de type vol !",
"The mysterious strong winds have dissipated!":"Les vents mystérieux se dissipent !",
"unleashes its full-force Z-Move!":" utilise sa capacité Z à pleine puissance !",
"bounced the":"a évité",
"back!":"!",
"Waggling a finger let it use":"Le métronome a lancé",
"Nature Power turned into":"Force-Nature s'est transformée en",
"Breakneck Blitz turned into":"",
"s attack continues!":" : L'attaque continue !",
"used Fissure!":"a utilisé abîme !",
"Just kidding! It was Earthquake!":"Ah mais non, c'était Séisme !",


"Register":"S'inscrire",
"Register your account:":"Inscrivez votre compte：",
"Username:":"Nom d'utilisateur ：",
"Password:":"Mot de passe ：",
"Password (confirm):":"Répéter le mot de passe :",
"What is this pokemon?":"Quel est ce pokémon ?",
"Cancel":"Annuler",
"Disconnected":"Déconnecter",
"Reconnect":"Reconnecter",

"If holder is an Altaria, this item allows it to Mega Evolve in battle.":"Si le porteur est Altaria, cet objet lui permet de Méga-Evoluer en combat.",
"If holder is an Abomasnow, this item allows it to Mega Evolve in battle.":"Si le porteur est Blizzaroi, cet objet lui permet de Méga-Evoluer en combat.",
"If holder is an Absol, this item allows it to Mega Evolve in battle.":"Si le porteur est Absol, cet objet lui permet de Méga-Evoluer en combat.",
"Raises holder's Sp. Atk by 1 stage if hit by a Water-type attack. Single use.":"Augmente l'attaque spéciale du porteur d'un niveau si celui-ci est touché par une attaque de type Eau. Usage unique.",
"If holder is a Dialga, its Steel- and Dragon-type attacks have 1.2x power.":"Si le porteur est Dialga, la force ses attaques de type Acier et Dragon augmente de 20%.",
"Raises holder's Speed by 1 stage if it gets affected by Intimidate. Single use.":"Augmente la vitesse du porteur d'un niveau, si celui-ci est affecté par Intimidation. Usage unique.",
"If holder is an Aerodactyl, this item allows it to Mega Evolve in battle.":"Si le porteur est Ptera, cet objet lui permet de Méga-Evoluer en combat.",
"If holder is an Aggron, this item allows it to Mega Evolve in battle.":"Si le porteur est Galeking, cet objet lui permet de Méga-Evoluer en combat.",
"Restores 1/2 max HP at 1/4 max HP or less; confuses if -SpD Nature. Single use.":"Redonne au maximum 50% des PV si donné quand les PV sont en dessous de 25%. Rend confus si sa nature est Vitesse. Usage unique.",
"Holder is immune to Ground-type attacks. Pops when holder is hit.":"Le porteur est immunisé contre les attaques de type sol. L'effet se termine quand le porteur est touché.",
"If holder is an Alakazam, this item allows it to Mega Evolve in battle.":"Si le porteur est Alakazam, cet objet lui permet de Méga-Evoluer en combat.",
"If holder is an Alolan Raichu with Thunderbolt, it can use Stoked Sparksurfer.":"Si le porteur est Raichu Alola avec Tonnerre, il peut utiliser Électro-Surf Survolté.",
"If holder is an Ampharos, this item allows it to Mega Evolve in battle.":"Si le porteur est Pharamp, cet objet lui permet de Méga-Evoluer en combat.",
"Raises holder's Sp. Def by 1 stage when at 1/4 max HP or less. Single use.":"Augmente la défense spéciale d'un niveau quand le porteur est à moins de 25% de PV restants. Usage unique.",
"Can be revived into Shieldon.":"Peut être ravivé en Dinoclier.",
"Holder is cured if it is frozen. Single use.":"Le porteur est dégelé. Usage unique.",
"Holder's Sp. Def is 1.5x, but it can only select damaging moves.":"La défense spéciale du porteur sera à 150% de l'originale, mais il n'est possible de choisir que des attaques infligeant des dommages.",
"If holder is an Audino, this item allows it to Mega Evolve in battle.":"Si le porteur est Nanméouïe, cet objet lui permet de Méga-Evoluer en combat.",
"Halves damage taken from a supereffective Steel-type attack. Single use.":"Diminue de moitié les dommages infligés par les attaques super efficaces de type Acier.",
"If holder is a Banette, this item allows it to Mega Evolve in battle.":"Si le porteur est Branette, cet objet lui permet de Méga-Evoluer en combat.",
"A special Poke Ball designed to catch Ultra Beasts.":"Une Poké Ball spéciale destinée à attraper les Ultra-Chimères.",
};

var QQ=$.noConflict();
var regex_ability=new RegExp(/Ability: ([A-za-z- ]+[A-za-z])$/);
var regex_possible_ability=new RegExp(/Possible abilities: ([A-za-z- ]+[A-za-z])$/);
var regex_possible_ability2=new RegExp(/Possible abilities: ([A-za-z- ]+[A-za-z]), ([A-za-z- ]+[A-za-z])$/);
var regex_Item=new RegExp(/Item: ([(A-za-z- ]+[A-za-z)])$/);
var regex_stat_change=new RegExp(/^'s ([A-za-z ]+)!/);
var regex_magic_bounce=new RegExp(/bounced the ([A-za-z -]+) back!/);
var regex_preview=new RegExp(/^([A-za-z* -]+ \/ )+([A-za-z* -]+)$/);
var regex_start_battle=new RegExp(/Battle between (.+) and (.+) started!/);
var regex_uturn=new RegExp(/went back to (.*)!/);
var regex_hurtby=new RegExp(/is hurt by ([A-Za-z- ]+)!/);
var regex_gems=new RegExp(/The ([A-za-z ]+) strengthened ([A-za-z- ]+)'s power!/);
var regex_eat=new RegExp(/ate its ([A-Za-z ]+)!/);
var regex_restorehp=new RegExp(/restored HP using its ([A-Za-z ]+)!/);
var t_= function(a){return a;}
var t= function(originalStr){
    var tmp=originalStr.trim();
    if(translations[tmp])
        return translations[tmp];
    if(tmp.indexOf("'s ")!=-1&&tmp.indexOf("!]")!=-1){
        tmp=tmp.replace("'s ","").replace("!]","");
        return "的"+translations[tmp]+"!]";
    }
    if(tmp.indexOf("sent out ")!=-1){
        var splitted=tmp.split(" sent out ");
        return splitted[0]+"放出了"+translations[splitted[1].replace("!","")]+"!";
    }
    if(tmp.indexOf(" withdrew ")!=-1){
        var splitted=tmp.split(" withdrew ");
        return splitted[0]+"收回了"+translations[splitted[1].replace("!","")]+"!";
    }
    if(tmp.indexOf("Go!")!=-1){
        return "去吧，"+translations[tmp.replace("Go! ","").replace("!","")]+"!";
    }
    //var regex=new RegExp(/(/)
    if(originalStr.match(regex_stat_change)){
        console.log(originalStr);
        var splitted=RegExp.$1.split(' ');
        var pos=splitted.length-1;
        var str2=splitted[pos--];
        while(!translations[str2]){
            str2=splitted[pos--]+" "+str2;
            if(pos<=0)break;
        }
        var str1=splitted[pos--];
        if(pos>=0)
            str1=splitted[pos--]+" "+str1;
        var ret="的";
        var trans1=translations[str1];
        var trans2=translations[str2];
        if(trans1)
            ret+=trans1;
        if(trans2)
            ret+=trans2;
        ret+="!";
        if(originalStr.indexOf("The opposing")!=-1)
            ret+=" 对手的";
        return ret;
    }
    if(originalStr.match(regex_ability)){
        originalStr=originalStr.replace(regex_ability,"特性: ");
        if(translations[RegExp.$1]){
            originalStr+=translations[RegExp.$1];
        }
        return originalStr;
    }
    if(originalStr.match(regex_possible_ability)){
        originalStr=originalStr.replace(regex_possible_ability,"可能的特性: ");
        if(translations[RegExp.$1]){
            originalStr+=translations[RegExp.$1];
        }
        return originalStr;
    }

    if(originalStr.match(regex_possible_ability2)){
        originalStr=originalStr.replace(regex_possible_ability2,"可能的特性: ");
        if(translations[RegExp.$1]&&translations[RegExp.$2]){
            originalStr=originalStr+translations[RegExp.$1]+"，"+translations[RegExp.$2];
        }
        return originalStr;
    }



    if(originalStr.match(regex_Item)){
        originalStr=originalStr.replace(regex_Item,"道具: ");
        if(translations[RegExp.$1]){
            originalStr+=translations[RegExp.$1];
        }
        return originalStr;
    }
    if(originalStr.match(regex_preview)){
        var pokes=originalStr.split(" / ");
        var ret=translations[pokes[0]];
        var pos=1;
        while(pokes[pos]){
            ret+=" / "+translations[pokes[pos]];
            pos++;
            if(pos>=6)break;
        }
        return ret;
    }
    if(originalStr.match(regex_start_battle)){
        return RegExp.$1+" 与 "+RegExp.$2+" 的对战开始了!";
    }
    if(originalStr.match(/^\((.*)\)$/)){
        if(translations[RegExp.$1])
            return "("+translations[RegExp.$1]+")";
    }
    if(originalStr.match(/has Mega Evolved into Mega ([A-za-z -]+)!/)){
        return "超级进化为Mega"+translations[RegExp.$1]+"!";
    }
    if(originalStr.match(/transformed into ([A-za-z -]+)!/)){
        return "变成了"+translations[RegExp.$1]+"!";
    }
    if(originalStr.match(regex_uturn)){
        return "回到了"+RegExp.$1+"的身边!";
    }
    if(originalStr.match(regex_hurtby)){
        var str1="因为";
        if(originalStr.indexOf("opposing"))
        return "因为"+translations[RegExp.$1]+"而受到了伤害!";
    }
    if(originalStr.match(regex_magic_bounce)){
        return "把"+translations[RegExp.$1]+"反弹回去了!";
    }
    if(originalStr.match(regex_magic_bounce)){
        return "把"+translations[RegExp.$1]+"反弹回去了!";
    }
    if(originalStr.match(/can't use ([A-za-z- ]+) after the taunt!/)){
        return "因为挑拨不能使用"+translations[RegExp.$1]+"!";
    }
    if(originalStr.match(regex_gems)){
        return translations[RegExp.$1]+"提升了"+translations[RegExp.$2]+"的威力!";
    }
    //else
        return originalStr
            .replace(/lost ([0-9]+)% of its health!/,"失去了$1%的生命值!")
            .replace(" sent out ","放出了 ")
            .replace("won the battle","获得了胜利")
            .replace(" withdrew ","收回了 ")
            .replace("forfeited","认输了")
            //.replace(/Ability: ([A-za-z ]+)/,"特性: "+translate(RegExp.$1))
            //.replace(/Ability: \/ Item: ([A-za-z ]+)/,"特性: "++"/ 道具:"+translate("$2"))
    ;

}
function translateElement(element){
    var elTW = document.createTreeWalker(element, NodeFilter.SHOW_Element, null, false);
    var node=null;
    var translate=t;
    while((node=elTW.nextNode())!=null){
        if(node.nodeValue){
            //console.log(QQ(node).text());
            //QQ(node).text(transl)
            //console.log(node.nodeValue+" "+node.parentNode.getAttribute("class"));
            //console.log();
            var value=node.nodeValue;
            if(value.indexOf('•')!=-1){     //技能名在鼠标移入的状态
                value=value.replace('•',"");
                value=translate(value);
                node.nodeValue="• "+value;
                continue;
            }
            else
                node.nodeValue=translate(node.nodeValue
                    .replace("held by","holder is")
            );
            //node=elTW.previousNode();
            //QQ(t).remove();
        }
    }
}

(function() {
    'use strict';
    if(document.getElementById('room-'))
        translateElement(document.getElementById('room-'));
    QQ(document).on('DOMNodeInserted',function(e){
        translateElement(e.target);
    });
    // Your code here...
})();
